<a href="https://colab.research.google.com/github/anushah-200/SATARK_AI/blob/main/notebooks/05_P1_Day2_Quality_Control_Fault_Injection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone "https://github.com/anushah-200/SATARK_AI"

Cloning into 'SATARK_AI'...
remote: Enumerating objects: 174, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 174 (delta 36), reused 31 (delta 31), pack-reused 133 (from 1)
Receiving objects: 100% (174/174), 8.12 MiB | 22.18 MiB/s, done.
Resolving deltas: 100% (71/71), done.

In [3]:
import os

print(os.listdir('/content/drive/MyDrive'))

['Colab Notebooks', 'Unit 2 (1).pdf', 'Unit 2 (2).pdf', 'halloween payment .jpg', 'Screenshot_2025-11-12-01-28-07-439_com.android.chrome.jpg', 'Screenshot_2025-11-12-01-30-10-308_com.whatsapp-edit.jpg', 'Unit-4(2).pdf', 'Unit-4(1).pdf', 'Untitled form.gform', '9625427415.jpeg', 'Screenshot_2026-01-08-23-42-56-965_com.whatsapp-edit.jpg', 'Charvi Bajaj MUN TASK1 screenshot folder', 'Untitled spreadsheet (2).gsheet', 'Classroom', 'id card charvi .pdf', 'Untitled spreadsheet (1).gsheet', 'N (1).pdf', 'N.pdf', '04701012025_CharviBajaj.pdf', 'Document.pdf', 'Scanned.pdf', 'Ranu gadi book (1).pdf', 'Ranu gadi book.pdf', 'MAD project.gdoc', 'work sample for bhav-charvi bajaj .docx', 'MAD-PPT-Template.pptx', 'Untitled presentation.gslides', 'Class Sync_MAD_Ppt(Group-6) (1).pdf', 'Class Sync_MAD_Ppt(Group-6).pdf', 'internship .gdoc', 'Untitled document.gdoc', 'factcheckAI', 'Project Progress Report.gdoc', 'IMG_20260717_125424.png', 'IMG_20260717_125743.png', '1784273865746.png', 'FACTCHECK AI.gdoc', 'Untitled spreadsheet.gsheet', 'Resume.gdoc', 'SATARK_AI']

In [4]:
PROJECT_PATH = "/content/drive/MyDrive/SATARK_AI"

print(os.listdir(PROJECT_PATH))

['data', 'models', 'notebooks', 'outputs', 'src']

In [5]:
import os

for root, dirs, files in os.walk(PROJECT_PATH):
    level = root.replace(PROJECT_PATH, '').count(os.sep)
    indent = '  ' * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}  └── {file}")

SATARK_AI/
  data/
    processed/
      └── processed_meteostat_data.csv
    raw/
      └── meteostat_data.csv
    synthetic/
      └── synthetic_fault_data.csv
  models/
  notebooks/
  outputs/
  src/
    └── spatial_analysis.py
    └── sensor_health.py
    └── diagnosis.py
    └── person3_pipeline.py

In [6]:
import pandas as pd
import os

RAW_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "raw",
    "meteostat_data.csv"
)

df_raw = pd.read_csv(RAW_PATH)

print("Shape:", df_raw.shape)
print("\nColumns:")
print(df_raw.columns.tolist())

print("\nFirst 5 rows:")
display(df_raw.head())

Shape: (43100, 10)

Columns:
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction']

First 5 rows:

,timestamp,station_id,station_name,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction
0,2025-01-01 00:00:00,42131,Hissar,29.1667,75.7333,5.4,97.0,1020.7,0.0,0.0
1,2025-01-01 01:00:00,42131,Hissar,29.1667,75.7333,6.1,98.0,1019.5,5.0,283.0
2,2025-01-01 02:00:00,42131,Hissar,29.1667,75.7333,6.1,94.0,1019.8,5.4,274.0
3,2025-01-01 03:00:00,42131,Hissar,29.1667,75.7333,8.0,97.0,1021.5,0.0,0.0
4,2025-01-01 04:00:00,42131,Hissar,29.1667,75.7333,7.6,96.0,1020.8,6.8,276.0

In [7]:
print("\nData types:")
print(df_raw.dtypes)

Data types:
timestamp          object
station_id          int64
station_name       object
latitude          float64
longitude         float64
temperature       float64
humidity          float64
pressure          float64
wind_speed        float64
wind_direction    float64
dtype: object

In [8]:
print("\nMissing values:")
print(df_raw.isna().sum())

Missing values:
timestamp           0
station_id          0
station_name        0
latitude            0
longitude           0
temperature         0
humidity            0
pressure            0
wind_speed          0
wind_direction    150
dtype: int64

In [9]:
print("\nBasic statistics:")
display(df_raw.describe())

Basic statistics:

,station_id,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction
count,43100.000000,43100.000000,43100.000000,43100.000000,43100.000000,43100.000000,43100.000000,42950.000000
mean,42162.005058,28.830599,76.856381,24.361745,67.884200,1008.333842,7.673914,187.247497
std,22.099854,0.236253,0.649409,7.864331,21.409544,7.234360,4.656795,99.277447
min,42131.000000,28.566700,75.733300,4.000000,5.000000,991.500000,0.000000,0.000000
25%,42139.000000,28.583300,76.583300,18.300000,53.000000,1002.100000,4.700000,100.000000
50%,42176.000000,28.833300,77.116700,26.000000,71.000000,1008.200000,7.200000,191.000000
75%,42181.000000,29.016700,77.200000,30.100000,85.000000,1014.800000,10.400000,280.000000
max,42182.000000,29.166700,77.633300,44.000000,100.000000,1026.300000,170.600000,360.000000

In [10]:
PROCESSED_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "processed",
    "processed_meteostat_data.csv"
)

df_processed = pd.read_csv(PROCESSED_PATH)

print("Shape:", df_processed.shape)

print("\nColumns:")
print(df_processed.columns.tolist())

print("\nFirst 5 rows:")
display(df_processed.head())

Shape: (43100, 28)

Columns:
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction', 'hour', 'day', 'month', 'day_of_week', 'day_of_year', 'time_period', 'temperature_rolling_mean_24h', 'temperature_rolling_std_24h', 'temperature_deviation_24h', 'temperature_zscore_24h', 'pressure_rolling_mean_24h', 'pressure_rolling_std_24h', 'pressure_deviation_24h', 'pressure_zscore_24h', 'humidity_rolling_mean_24h', 'humidity_rolling_std_24h', 'humidity_deviation_24h', 'humidity_zscore_24h']

First 5 rows:

,timestamp,station_id,station_name,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction,...,temperature_deviation_24h,temperature_zscore_24h,pressure_rolling_mean_24h,pressure_rolling_std_24h,pressure_deviation_24h,pressure_zscore_24h,humidity_rolling_mean_24h,humidity_rolling_std_24h,humidity_deviation_24h,humidity_zscore_24h
0,2025-01-01 00:00:00,42131,Hissar,29.1667,75.7333,5.4,97.0,1020.7,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-01 01:00:00,42131,Hissar,29.1667,75.7333,6.1,98.0,1019.5,5.0,283.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-01-01 02:00:00,42131,Hissar,29.1667,75.7333,6.1,94.0,1019.8,5.4,274.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-01-01 03:00:00,42131,Hissar,29.1667,75.7333,8.0,97.0,1021.5,0.0,0.0,...,2.133333,5.278631,1020.000,0.624500,1.500,2.401922,96.333333,2.081666,0.666667,0.320256
4,2025-01-01 04:00:00,42131,Hissar,29.1667,75.7333,7.6,96.0,1020.8,6.8,276.0,...,1.200000,1.074747,1020.375,0.906918,0.425,0.468620,96.500000,1.732051,-0.500000,-0.288675

In [11]:
print("\nMissing values:")
print(df_processed.isna().sum())

Missing values:
timestamp                         0
station_id                        0
station_name                      0
latitude                          0
longitude                         0
temperature                       0
humidity                          0
pressure                          0
wind_speed                        0
wind_direction                  150
hour                              0
day                               0
month                             0
day_of_week                       0
day_of_year                       0
time_period                       0
temperature_rolling_mean_24h     15
temperature_rolling_std_24h      15
temperature_deviation_24h        15
temperature_zscore_24h           15
pressure_rolling_mean_24h        15
pressure_rolling_std_24h         15
pressure_deviation_24h           15
pressure_zscore_24h              15
humidity_rolling_mean_24h        15
humidity_rolling_std_24h         15
humidity_deviation_24h           15
humidity_zscore_24h              16
dtype: int64

In [12]:
SYNTHETIC_PATH = os.path.join(
    PROJECT_PATH,
    "data",
    "synthetic",
    "synthetic_fault_data.csv"
)

df_synthetic = pd.read_csv(SYNTHETIC_PATH)

print("Shape:", df_synthetic.shape)

print("\nColumns:")
print(df_synthetic.columns.tolist())

print("\nFirst 10 rows:")
display(df_synthetic.head(10))

Shape: (43100, 34)

Columns:
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction', 'hour', 'day', 'month', 'day_of_week', 'day_of_year', 'time_period', 'temperature_rolling_mean_24h', 'temperature_rolling_std_24h', 'temperature_deviation_24h', 'temperature_zscore_24h', 'pressure_rolling_mean_24h', 'pressure_rolling_std_24h', 'pressure_deviation_24h', 'pressure_zscore_24h', 'humidity_rolling_mean_24h', 'humidity_rolling_std_24h', 'humidity_deviation_24h', 'humidity_zscore_24h', 'original_temperature', 'original_pressure', 'original_humidity', 'is_anomaly', 'fault_type', 'fault_severity']

First 10 rows:

,timestamp,station_id,station_name,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction,...,humidity_rolling_mean_24h,humidity_rolling_std_24h,humidity_deviation_24h,humidity_zscore_24h,original_temperature,original_pressure,original_humidity,is_anomaly,fault_type,fault_severity
0,2025-01-01 00:00:00,42131,Hissar,29.1667,75.7333,5.4,97.0,1020.7,0.0,0.0,...,NaN,NaN,NaN,NaN,5.4,1020.7,97.0,0,normal,none
1,2025-01-01 01:00:00,42131,Hissar,29.1667,75.7333,6.1,98.0,1019.5,5.0,283.0,...,NaN,NaN,NaN,NaN,6.1,1019.5,98.0,0,normal,none
2,2025-01-01 02:00:00,42131,Hissar,29.1667,75.7333,6.1,94.0,1019.8,5.4,274.0,...,NaN,NaN,NaN,NaN,6.1,1019.8,94.0,0,normal,none
3,2025-01-01 03:00:00,42131,Hissar,29.1667,75.7333,8.0,97.0,1021.5,0.0,0.0,...,96.333333,2.081666,0.666667,0.320256,8.0,1021.5,97.0,0,normal,none
4,2025-01-01 04:00:00,42131,Hissar,29.1667,75.7333,7.6,96.0,1020.8,6.8,276.0,...,96.500000,1.732051,-0.500000,-0.288675,7.6,1020.8,96.0,0,normal,none
5,2025-01-01 05:00:00,42131,Hissar,29.1667,75.7333,9.8,94.0,1021.0,6.5,292.0,...,96.400000,1.516575,-2.400000,-1.582513,9.8,1021.0,94.0,0,normal,none
6,2025-01-01 06:00:00,42131,Hissar,29.1667,75.7333,10.0,92.0,1022.1,3.6,320.0,...,96.000000,1.673320,-4.000000,-2.390457,10.0,1022.1,92.0,0,normal,none
7,2025-01-01 07:00:00,42131,Hissar,29.1667,75.7333,14.9,72.0,1019.7,6.8,289.0,...,95.428571,2.149197,-23.428571,-10.901082,14.9,1019.7,72.0,0,normal,none
8,2025-01-01 08:00:00,42131,Hissar,29.1667,75.7333,16.3,65.0,1018.4,7.9,291.0,...,92.500000,8.518887,-27.500000,-3.228121,16.3,1018.4,65.0,0,normal,none
9,2025-01-01 09:00:00,42131,Hissar,29.1667,75.7333,11.8,81.0,1019.1,3.6,320.0,...,89.444444,12.146101,-8.444444,-0.695239,11.8,1019.1,81.0,0,normal,none

In [13]:
print("\nData types:")
print(df_synthetic.dtypes)

Data types:
timestamp                        object
station_id                        int64
station_name                     object
latitude                        float64
longitude                       float64
temperature                     float64
humidity                        float64
pressure                        float64
wind_speed                      float64
wind_direction                  float64
hour                              int64
day                               int64
month                             int64
day_of_week                       int64
day_of_year                       int64
time_period                      object
temperature_rolling_mean_24h    float64
temperature_rolling_std_24h     float64
temperature_deviation_24h       float64
temperature_zscore_24h          float64
pressure_rolling_mean_24h       float64
pressure_rolling_std_24h        float64
pressure_deviation_24h          float64
pressure_zscore_24h             float64
humidity_rolling_mean_24h       float64
humidity_rolling_std_24h        float64
humidity_deviation_24h          float64
humidity_zscore_24h             float64
original_temperature            float64
original_pressure               float64
original_humidity               float64
is_anomaly                        int64
fault_type                       object
fault_severity                   object
dtype: object

In [14]:
print("\nMissing values:")
print(df_synthetic.isna().sum())

Missing values:
timestamp                         0
station_id                        0
station_name                      0
latitude                          0
longitude                         0
temperature                      26
humidity                          9
pressure                         26
wind_speed                        0
wind_direction                  150
hour                              0
day                               0
month                             0
day_of_week                       0
day_of_year                       0
time_period                       0
temperature_rolling_mean_24h     15
temperature_rolling_std_24h      15
temperature_deviation_24h        15
temperature_zscore_24h           15
pressure_rolling_mean_24h        15
pressure_rolling_std_24h         15
pressure_deviation_24h           15
pressure_zscore_24h              15
humidity_rolling_mean_24h        15
humidity_rolling_std_24h         15
humidity_deviation_24h           15
humidity_zscore_24h              16
original_temperature              0
original_pressure                 0
original_humidity                 0
is_anomaly                        0
fault_type                        0
fault_severity                    0
dtype: int64

In [15]:
print("Fault types:")
print(df_synthetic["fault_type"].value_counts(dropna=False))

Fault types:
fault_type
normal                        42778
multivariate_inconsistency       60
temperature_missing              26
pressure_missing                 26
pressure_spike                   25
pressure_drift                   24
temperature_frozen               22
humidity_drift                   22
humidity_frozen                  21
temperature_drift                19
humidity_spike                   18
temperature_spike                15
humidity_drop                    12
pressure_frozen                  10
humidity_missing                  9
temperature_drop                  9
pressure_drop                     4
Name: count, dtype: int64

In [16]:
print("\nFault severity:")
print(df_synthetic["fault_severity"].value_counts(dropna=False))

Fault severity:
fault_severity
none        42778
moderate      113
mild          106
severe        103
Name: count, dtype: int64

In [17]:
print("\nAnomaly counts:")
print(df_synthetic["is_anomaly"].value_counts())

Anomaly counts:
is_anomaly
0    42778
1      322
Name: count, dtype: int64

In [18]:
display(
    df_synthetic[
        [
            "timestamp",
            "station_id",
            "station_name",
            "temperature",
            "original_temperature",
            "humidity",
            "original_humidity",
            "pressure",
            "original_pressure",
            "is_anomaly",
            "fault_type",
            "fault_severity"
        ]
    ].query("is_anomaly == 1").head(30)
)

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,is_anomaly,fault_type,fault_severity
512,2025-01-22 08:00:00,42131,Hissar,20.5,20.5,63.0,63.0,1003.7,1013.7,1,pressure_drop,moderate
513,2025-01-22 09:00:00,42131,Hissar,22.8,22.8,43.0,43.0,1003.2,1013.2,1,pressure_drop,moderate
1069,2025-02-14 13:00:00,42131,Hissar,18.0,18.0,71.0,71.0,1012.1,1011.6,1,pressure_drift,moderate
1070,2025-02-14 14:00:00,42131,Hissar,17.7,17.7,67.0,67.0,1012.8,1011.8,1,pressure_drift,moderate
1071,2025-02-14 15:00:00,42131,Hissar,16.2,16.2,68.0,68.0,1015.5,1014.0,1,pressure_drift,moderate
1072,2025-02-14 16:00:00,42131,Hissar,16.4,16.4,63.0,63.0,1014.2,1012.2,1,pressure_drift,moderate
1073,2025-02-14 17:00:00,42131,Hissar,15.1,15.1,65.0,65.0,1014.6,1012.1,1,pressure_drift,moderate
1074,2025-02-14 18:00:00,42131,Hissar,14.8,14.8,70.0,70.0,1016.3,1013.3,1,pressure_drift,moderate
1816,2025-03-22 05:00:00,42131,Hissar,26.0,26.0,41.0,41.0,1014.5,1014.5,1,humidity_frozen,moderate
1817,2025-03-22 06:00:00,42131,Hissar,30.2,30.2,41.0,41.0,1015.5,1015.5,1,humidity_frozen,moderate
1853,2025-03-23 18:00:00,42131,Hissar,18.4,18.4,79.0,79.0,1016.3,1016.1,1,pressure_drift,mild
2049,2025-03-31 22:00:00,42131,Hissar,17.5,17.5,38.0,38.0,1008.4,1008.2,1,pressure_drift,mild
2368,2025-04-14 05:00:00,42131,Hissar,33.8,33.8,27.2,27.0,1009.2,1009.2,1,humidity_drift,mild
2369,2025-04-14 06:00:00,42131,Hissar,35.2,35.2,24.4,24.0,1008.7,1008.7,1,humidity_drift,mild
2370,2025-04-14 07:00:00,42131,Hissar,35.7,35.7,24.6,24.0,1008.2,1008.2,1,humidity_drift,mild
2371,2025-04-14 08:00:00,42131,Hissar,36.2,36.2,23.8,23.0,1007.4,1007.4,1,humidity_drift,mild
2681,2025-05-01 07:00:00,42131,Hissar,18.3,38.3,23.0,23.0,1006.6,1006.6,1,temperature_drop,severe
2682,2025-05-01 08:00:00,42131,Hissar,19.1,39.1,19.0,19.0,1006.1,1006.1,1,temperature_drop,severe
3343,2025-05-28 21:00:00,42131,Hissar,28.6,28.6,NaN,61.0,995.8,995.8,1,humidity_missing,mild
3344,2025-05-28 22:00:00,42131,Hissar,31.3,31.3,NaN,44.0,994.9,994.9,1,humidity_missing,mild
3345,2025-05-28 23:00:00,42131,Hissar,30.5,30.5,NaN,45.0,995.3,995.3,1,humidity_missing,mild
3346,2025-05-29 00:00:00,42131,Hissar,29.3,29.3,NaN,47.0,995.7,995.7,1,humidity_missing,mild
3347,2025-05-29 01:00:00,42131,Hissar,29.7,29.7,NaN,56.0,996.6,996.6,1,humidity_missing,mild
3348,2025-05-29 02:00:00,42131,Hissar,31.2,31.2,NaN,44.0,997.0,997.0,1,humidity_missing,mild
3440,2025-06-01 22:00:00,42131,Hissar,30.9,25.9,43.0,43.0,996.4,996.4,1,multivariate_inconsistency,mild
3441,2025-06-01 23:00:00,42131,Hissar,30.3,25.3,45.0,45.0,996.6,996.6,1,multivariate_inconsistency,mild
3442,2025-06-02 00:00:00,42131,Hissar,29.1,24.1,51.0,51.0,997.1,997.1,1,multivariate_inconsistency,mild
3443,2025-06-02 01:00:00,42131,Hissar,29.5,24.5,54.0,54.0,997.7,997.7,1,multivariate_inconsistency,mild
3444,2025-06-02 02:00:00,42131,Hissar,34.1,29.1,49.0,49.0,998.2,998.2,1,multivariate_inconsistency,mild
3445,2025-06-02 03:00:00,42131,Hissar,36.0,31.0,45.0,45.0,998.6,998.6,1,multivariate_inconsistency,mild

In [19]:
df_raw["timestamp"] = pd.to_datetime(df_raw["timestamp"])

print(
    df_raw
    .sort_values(["station_id", "timestamp"])
    .groupby("station_id")["timestamp"]
    .diff()
    .value_counts()
    .head(10)
)

timestamp
0 days 01:00:00    42891
0 days 03:00:00       99
0 days 06:00:00       99
0 days 02:00:00        3
0 days 04:00:00        3
Name: count, dtype: int64

In [20]:
print("Fault type distribution:")
print(df_synthetic["fault_type"].value_counts(dropna=False))

Fault type distribution:
fault_type
normal                        42778
multivariate_inconsistency       60
temperature_missing              26
pressure_missing                 26
pressure_spike                   25
pressure_drift                   24
temperature_frozen               22
humidity_drift                   22
humidity_frozen                  21
temperature_drift                19
humidity_spike                   18
temperature_spike                15
humidity_drop                    12
pressure_frozen                  10
humidity_missing                  9
temperature_drop                  9
pressure_drop                     4
Name: count, dtype: int64

In [21]:
display(
    df_synthetic[
        [
            "timestamp",
            "station_id",
            "station_name",
            "temperature",
            "original_temperature",
            "humidity",
            "original_humidity",
            "pressure",
            "original_pressure",
            "is_anomaly",
            "fault_type",
            "fault_severity"
        ]
    ]
    .query("is_anomaly == 1")
    .head(30)
)

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,is_anomaly,fault_type,fault_severity
512,2025-01-22 08:00:00,42131,Hissar,20.5,20.5,63.0,63.0,1003.7,1013.7,1,pressure_drop,moderate
513,2025-01-22 09:00:00,42131,Hissar,22.8,22.8,43.0,43.0,1003.2,1013.2,1,pressure_drop,moderate
1069,2025-02-14 13:00:00,42131,Hissar,18.0,18.0,71.0,71.0,1012.1,1011.6,1,pressure_drift,moderate
1070,2025-02-14 14:00:00,42131,Hissar,17.7,17.7,67.0,67.0,1012.8,1011.8,1,pressure_drift,moderate
1071,2025-02-14 15:00:00,42131,Hissar,16.2,16.2,68.0,68.0,1015.5,1014.0,1,pressure_drift,moderate
1072,2025-02-14 16:00:00,42131,Hissar,16.4,16.4,63.0,63.0,1014.2,1012.2,1,pressure_drift,moderate
1073,2025-02-14 17:00:00,42131,Hissar,15.1,15.1,65.0,65.0,1014.6,1012.1,1,pressure_drift,moderate
1074,2025-02-14 18:00:00,42131,Hissar,14.8,14.8,70.0,70.0,1016.3,1013.3,1,pressure_drift,moderate
1816,2025-03-22 05:00:00,42131,Hissar,26.0,26.0,41.0,41.0,1014.5,1014.5,1,humidity_frozen,moderate
1817,2025-03-22 06:00:00,42131,Hissar,30.2,30.2,41.0,41.0,1015.5,1015.5,1,humidity_frozen,moderate
1853,2025-03-23 18:00:00,42131,Hissar,18.4,18.4,79.0,79.0,1016.3,1016.1,1,pressure_drift,mild
2049,2025-03-31 22:00:00,42131,Hissar,17.5,17.5,38.0,38.0,1008.4,1008.2,1,pressure_drift,mild
2368,2025-04-14 05:00:00,42131,Hissar,33.8,33.8,27.2,27.0,1009.2,1009.2,1,humidity_drift,mild
2369,2025-04-14 06:00:00,42131,Hissar,35.2,35.2,24.4,24.0,1008.7,1008.7,1,humidity_drift,mild
2370,2025-04-14 07:00:00,42131,Hissar,35.7,35.7,24.6,24.0,1008.2,1008.2,1,humidity_drift,mild
2371,2025-04-14 08:00:00,42131,Hissar,36.2,36.2,23.8,23.0,1007.4,1007.4,1,humidity_drift,mild
2681,2025-05-01 07:00:00,42131,Hissar,18.3,38.3,23.0,23.0,1006.6,1006.6,1,temperature_drop,severe
2682,2025-05-01 08:00:00,42131,Hissar,19.1,39.1,19.0,19.0,1006.1,1006.1,1,temperature_drop,severe
3343,2025-05-28 21:00:00,42131,Hissar,28.6,28.6,NaN,61.0,995.8,995.8,1,humidity_missing,mild
3344,2025-05-28 22:00:00,42131,Hissar,31.3,31.3,NaN,44.0,994.9,994.9,1,humidity_missing,mild
3345,2025-05-28 23:00:00,42131,Hissar,30.5,30.5,NaN,45.0,995.3,995.3,1,humidity_missing,mild
3346,2025-05-29 00:00:00,42131,Hissar,29.3,29.3,NaN,47.0,995.7,995.7,1,humidity_missing,mild
3347,2025-05-29 01:00:00,42131,Hissar,29.7,29.7,NaN,56.0,996.6,996.6,1,humidity_missing,mild
3348,2025-05-29 02:00:00,42131,Hissar,31.2,31.2,NaN,44.0,997.0,997.0,1,humidity_missing,mild
3440,2025-06-01 22:00:00,42131,Hissar,30.9,25.9,43.0,43.0,996.4,996.4,1,multivariate_inconsistency,mild
3441,2025-06-01 23:00:00,42131,Hissar,30.3,25.3,45.0,45.0,996.6,996.6,1,multivariate_inconsistency,mild
3442,2025-06-02 00:00:00,42131,Hissar,29.1,24.1,51.0,51.0,997.1,997.1,1,multivariate_inconsistency,mild
3443,2025-06-02 01:00:00,42131,Hissar,29.5,24.5,54.0,54.0,997.7,997.7,1,multivariate_inconsistency,mild
3444,2025-06-02 02:00:00,42131,Hissar,34.1,29.1,49.0,49.0,998.2,998.2,1,multivariate_inconsistency,mild
3445,2025-06-02 03:00:00,42131,Hissar,36.0,31.0,45.0,45.0,998.6,998.6,1,multivariate_inconsistency,mild

In [22]:
print("Faults by station:")
display(
    pd.crosstab(
        df_synthetic["station_id"],
        df_synthetic["fault_type"]
    )
)

Faults by station:

fault_type,humidity_drift,humidity_drop,humidity_frozen,humidity_missing,humidity_spike,multivariate_inconsistency,normal,pressure_drift,pressure_drop,pressure_frozen,pressure_missing,pressure_spike,temperature_drift,temperature_drop,temperature_frozen,temperature_missing,temperature_spike
station_id,,,,,,,,,,,,,,,,,
42131,10,0,2,6,0,6,8460,13,2,0,4,10,6,2,10,6,0
42139,3,0,4,0,0,14,8483,8,0,0,4,0,0,1,5,1,1
42176,0,0,2,2,6,11,8469,0,2,0,10,0,7,3,0,0,5
42181,2,12,9,0,12,19,8669,0,0,10,2,2,5,3,1,11,4
42182,7,0,4,1,0,10,8697,3,0,0,6,13,1,0,6,8,5

In [23]:
fault_types = [
    "temperature_spike",
    "temperature_drop",
    "temperature_drift",
    "temperature_frozen",
    "temperature_missing",
    "humidity_spike",
    "humidity_drop",
    "humidity_drift",
    "humidity_frozen",
    "humidity_missing",
    "pressure_spike",
    "pressure_drop",
    "pressure_drift",
    "pressure_frozen",
    "pressure_missing",
    "multivariate_inconsistency"
]

for fault in fault_types:
    print(f"\n===== {fault} =====")

    display(
        df_synthetic[
            df_synthetic["fault_type"] == fault
        ][
            [
                "timestamp",
                "station_id",
                "station_name",
                "temperature",
                "original_temperature",
                "humidity",
                "original_humidity",
                "pressure",
                "original_pressure",
                "fault_type",
                "fault_severity"
            ]
        ].head(5)
    )

===== temperature_spike =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
16692,2025-12-16 16:00:00,42139,Meerut,32.8,12.8,85.0,85.0,1017.0,1017.0,temperature_spike,severe
22238,2025-08-14 03:00:00,42176,Rohtak,48.6,28.6,93.0,93.0,1004.7,1004.7,temperature_spike,severe
22239,2025-08-14 04:00:00,42176,Rohtak,48.9,28.9,91.0,91.0,1005.0,1005.0,temperature_spike,severe
24446,2025-11-14 21:00:00,42176,Rohtak,18.8,13.8,71.0,71.0,1016.4,1016.4,temperature_spike,mild
24447,2025-11-14 22:00:00,42176,Rohtak,18.3,13.3,76.0,76.0,1016.3,1016.3,temperature_spike,mild

===== temperature_drop =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
2681,2025-05-01 07:00:00,42131,Hissar,18.3,38.3,23.0,23.0,1006.6,1006.6,temperature_drop,severe
2682,2025-05-01 08:00:00,42131,Hissar,19.1,39.1,19.0,19.0,1006.1,1006.1,temperature_drop,severe
16395,2025-12-04 07:00:00,42139,Meerut,14.0,19.0,53.0,53.0,1019.0,1019.0,temperature_drop,mild
21672,2025-07-21 13:00:00,42176,Rohtak,25.4,30.4,82.0,82.0,998.9,998.9,temperature_drop,mild
21673,2025-07-21 14:00:00,42176,Rohtak,24.7,29.7,84.0,84.0,999.4,999.4,temperature_drop,mild

===== temperature_drift =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
3854,2025-06-19 04:00:00,42131,Hissar,33.2,32.7,61.0,61.0,996.9,996.9,temperature_drift,moderate
3855,2025-06-19 05:00:00,42131,Hissar,35.0,34.0,55.0,55.0,996.7,996.7,temperature_drift,moderate
3856,2025-06-19 06:00:00,42131,Hissar,36.6,35.1,48.0,48.0,996.6,996.6,temperature_drift,moderate
7400,2025-11-14 16:00:00,42131,Hissar,15.5,15.3,63.0,63.0,1017.3,1017.3,temperature_drift,mild
7401,2025-11-14 17:00:00,42131,Hissar,15.1,14.7,64.0,64.0,1017.4,1017.4,temperature_drift,mild

===== temperature_frozen =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
3561,2025-06-06 23:00:00,42131,Hissar,27.0,27.0,57.0,57.0,1003.4,1003.4,temperature_frozen,mild
3562,2025-06-07 00:00:00,42131,Hissar,27.0,26.7,56.0,56.0,1003.9,1003.9,temperature_frozen,mild
5575,2025-08-29 21:00:00,42131,Hissar,26.6,26.6,90.0,90.0,1004.5,1004.5,temperature_frozen,severe
5576,2025-08-29 22:00:00,42131,Hissar,26.6,26.5,90.0,90.0,1004.4,1004.4,temperature_frozen,severe
5577,2025-08-29 23:00:00,42131,Hissar,26.6,26.3,91.0,91.0,1004.2,1004.2,temperature_frozen,severe

===== temperature_missing =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
7419,2025-11-15 11:00:00,42131,Hissar,NaN,23.1,47.0,47.0,1016.8,1016.8,temperature_missing,moderate
7420,2025-11-15 12:00:00,42131,Hissar,NaN,19.9,46.0,46.0,1016.9,1016.9,temperature_missing,moderate
7421,2025-11-15 13:00:00,42131,Hissar,NaN,18.2,50.0,50.0,1017.3,1017.3,temperature_missing,moderate
7683,2025-11-26 11:00:00,42131,Hissar,NaN,20.5,60.0,60.0,1017.9,1017.9,temperature_missing,mild
7684,2025-11-26 12:00:00,42131,Hissar,NaN,18.2,58.0,58.0,1018.1,1018.1,temperature_missing,mild

===== humidity_spike =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
21343,2025-07-07 20:00:00,42176,Rohtak,29.5,29.5,92.0,82.0,998.5,998.5,humidity_spike,mild
21344,2025-07-07 21:00:00,42176,Rohtak,28.6,28.6,95.0,85.0,998.4,998.4,humidity_spike,mild
21345,2025-07-07 22:00:00,42176,Rohtak,28.5,28.5,95.0,85.0,997.9,997.9,humidity_spike,mild
21346,2025-07-07 23:00:00,42176,Rohtak,28.4,28.4,95.0,85.0,998.2,998.2,humidity_spike,mild
21347,2025-07-08 00:00:00,42176,Rohtak,28.4,28.4,95.0,85.0,998.9,998.9,humidity_spike,mild

===== humidity_drop =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
28057,2025-04-14 07:00:00,42181,Palam,35.0,35.0,2.0,27.0,1010.0,1010.0,humidity_drop,moderate
28058,2025-04-14 08:00:00,42181,Palam,36.0,36.0,0.0,25.0,1009.0,1009.0,humidity_drop,moderate
28059,2025-04-14 09:00:00,42181,Palam,36.0,36.0,-1.0,24.0,1008.0,1008.0,humidity_drop,moderate
28060,2025-04-14 10:00:00,42181,Palam,36.0,36.0,-1.0,24.0,1008.0,1008.0,humidity_drop,moderate
28061,2025-04-14 11:00:00,42181,Palam,35.0,35.0,0.0,25.0,1008.0,1008.0,humidity_drop,moderate

===== humidity_drift =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
2368,2025-04-14 05:00:00,42131,Hissar,33.8,33.8,27.2,27.0,1009.2,1009.2,humidity_drift,mild
2369,2025-04-14 06:00:00,42131,Hissar,35.2,35.2,24.4,24.0,1008.7,1008.7,humidity_drift,mild
2370,2025-04-14 07:00:00,42131,Hissar,35.7,35.7,24.6,24.0,1008.2,1008.2,humidity_drift,mild
2371,2025-04-14 08:00:00,42131,Hissar,36.2,36.2,23.8,23.0,1007.4,1007.4,humidity_drift,mild
7208,2025-11-06 16:00:00,42131,Hissar,17.5,17.5,49.2,49.0,1014.3,1014.3,humidity_drift,mild

===== humidity_frozen =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
1816,2025-03-22 05:00:00,42131,Hissar,26.0,26.0,41.0,41.0,1014.5,1014.5,humidity_frozen,moderate
1817,2025-03-22 06:00:00,42131,Hissar,30.2,30.2,41.0,41.0,1015.5,1015.5,humidity_frozen,moderate
12400,2025-06-20 02:00:00,42139,Meerut,26.6,26.6,89.0,89.0,999.8,999.8,humidity_frozen,moderate
12401,2025-06-20 03:00:00,42139,Meerut,26.8,26.8,89.0,87.0,1000.5,1000.5,humidity_frozen,moderate
15508,2025-10-28 08:00:00,42139,Meerut,26.5,26.5,57.0,57.0,1013.8,1013.8,humidity_frozen,moderate

===== humidity_missing =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
3343,2025-05-28 21:00:00,42131,Hissar,28.6,28.6,NaN,61.0,995.8,995.8,humidity_missing,mild
3344,2025-05-28 22:00:00,42131,Hissar,31.3,31.3,NaN,44.0,994.9,994.9,humidity_missing,mild
3345,2025-05-28 23:00:00,42131,Hissar,30.5,30.5,NaN,45.0,995.3,995.3,humidity_missing,mild
3346,2025-05-29 00:00:00,42131,Hissar,29.3,29.3,NaN,47.0,995.7,995.7,humidity_missing,mild
3347,2025-05-29 01:00:00,42131,Hissar,29.7,29.7,NaN,56.0,996.6,996.6,humidity_missing,mild

===== pressure_spike =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
4737,2025-07-25 23:00:00,42131,Hissar,27.6,27.6,94.0,94.0,1015.6,995.6,pressure_spike,severe
4738,2025-07-26 00:00:00,42131,Hissar,27.5,27.5,94.0,94.0,1016.1,996.1,pressure_spike,severe
4739,2025-07-26 01:00:00,42131,Hissar,27.7,27.7,87.0,87.0,1016.3,996.3,pressure_spike,severe
4740,2025-07-26 02:00:00,42131,Hissar,28.3,28.3,85.0,85.0,1016.8,996.8,pressure_spike,severe
7343,2025-11-12 07:00:00,42131,Hissar,25.9,25.9,34.0,34.0,1035.7,1015.7,pressure_spike,severe

===== pressure_drop =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
512,2025-01-22 08:00:00,42131,Hissar,20.5,20.5,63.0,63.0,1003.7,1013.7,pressure_drop,moderate
513,2025-01-22 09:00:00,42131,Hissar,22.8,22.8,43.0,43.0,1003.2,1013.2,pressure_drop,moderate
23809,2025-10-19 08:00:00,42176,Rohtak,32.5,32.5,37.0,37.0,990.9,1010.9,pressure_drop,severe
23810,2025-10-19 09:00:00,42176,Rohtak,32.5,32.5,37.0,37.0,989.9,1009.9,pressure_drop,severe

===== pressure_drift =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
1069,2025-02-14 13:00:00,42131,Hissar,18.0,18.0,71.0,71.0,1012.1,1011.6,pressure_drift,moderate
1070,2025-02-14 14:00:00,42131,Hissar,17.7,17.7,67.0,67.0,1012.8,1011.8,pressure_drift,moderate
1071,2025-02-14 15:00:00,42131,Hissar,16.2,16.2,68.0,68.0,1015.5,1014.0,pressure_drift,moderate
1072,2025-02-14 16:00:00,42131,Hissar,16.4,16.4,63.0,63.0,1014.2,1012.2,pressure_drift,moderate
1073,2025-02-14 17:00:00,42131,Hissar,15.1,15.1,65.0,65.0,1014.6,1012.1,pressure_drift,moderate

===== pressure_frozen =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
26347,2025-02-02 01:00:00,42181,Palam,12.0,12.0,100.0,100.0,1015.0,1015.0,pressure_frozen,moderate
26348,2025-02-02 02:00:00,42181,Palam,12.0,12.0,100.0,100.0,1015.0,1016.0,pressure_frozen,moderate
26349,2025-02-02 03:00:00,42181,Palam,12.4,12.4,95.0,95.0,1015.0,1017.8,pressure_frozen,moderate
26350,2025-02-02 04:00:00,42181,Palam,12.0,12.0,100.0,100.0,1015.0,1018.0,pressure_frozen,moderate
29967,2025-07-02 21:00:00,42181,Palam,29.0,29.0,89.0,89.0,1000.0,1000.0,pressure_frozen,severe

===== pressure_missing =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
5222,2025-08-15 04:00:00,42131,Hissar,29.5,29.5,76.0,76.0,NaN,1004.3,pressure_missing,mild
5223,2025-08-15 05:00:00,42131,Hissar,30.5,30.5,72.0,72.0,NaN,1004.1,pressure_missing,mild
5224,2025-08-15 06:00:00,42131,Hissar,31.4,31.4,70.0,70.0,NaN,1004.1,pressure_missing,mild
5225,2025-08-15 07:00:00,42131,Hissar,32.1,32.1,67.0,67.0,NaN,1003.5,pressure_missing,mild
11230,2025-05-02 08:00:00,42139,Meerut,30.2,30.2,51.0,51.0,NaN,1009.3,pressure_missing,moderate

===== multivariate_inconsistency =====

,timestamp,station_id,station_name,temperature,original_temperature,humidity,original_humidity,pressure,original_pressure,fault_type,fault_severity
3440,2025-06-01 22:00:00,42131,Hissar,30.9,25.9,43.0,43.0,996.4,996.4,multivariate_inconsistency,mild
3441,2025-06-01 23:00:00,42131,Hissar,30.3,25.3,45.0,45.0,996.6,996.6,multivariate_inconsistency,mild
3442,2025-06-02 00:00:00,42131,Hissar,29.1,24.1,51.0,51.0,997.1,997.1,multivariate_inconsistency,mild
3443,2025-06-02 01:00:00,42131,Hissar,29.5,24.5,54.0,54.0,997.7,997.7,multivariate_inconsistency,mild
3444,2025-06-02 02:00:00,42131,Hissar,34.1,29.1,49.0,49.0,998.2,998.2,multivariate_inconsistency,mild

In [24]:
import os

for root, dirs, files in os.walk(PROJECT_PATH):
    for file in files:
        if file.endswith(".py") or file.endswith(".ipynb"):
            print(os.path.join(root, file))

/content/drive/MyDrive/SATARK_AI/src/spatial_analysis.py
/content/drive/MyDrive/SATARK_AI/src/sensor_health.py
/content/drive/MyDrive/SATARK_AI/src/diagnosis.py
/content/drive/MyDrive/SATARK_AI/src/person3_pipeline.py

In [25]:
REPO_PATH = "/content/SATARK_AI"

print(os.listdir(REPO_PATH))

['dashboard', 'README.md', '.git', 'docs', '.gitignore', 'tests', 'requirements.txt', 'LICENSE', 'outputs', 'notebooks', 'src', 'data']

In [26]:
SRC_PATH = os.path.join(REPO_PATH, "src")
print(os.listdir(SRC_PATH))

['data_preprocessing.py', 'quality_control.py', 'sensor_health.py', 'fault_injection.py', 'anomaly_detector.py', 'anomaly_detection.py', 'spatial_analysis.py', '__init__.py', 'person3_pipeline.py', 'diagnosis.py', 'evaluate_model.py']

In [27]:
import os

PERSON1_FILES = [
    "data_preprocessing.py",
    "quality_control.py",
    "fault_injection.py"
]

for filename in PERSON1_FILES:
    filepath = os.path.join(SRC_PATH, filename)

    print("\n" + "=" * 70)
    print(f"FILE: {filename}")
    print("=" * 70)

    with open(filepath, "r") as f:
        print(f.read())

======================================================================
FILE: data_preprocessing.py
======================================================================



======================================================================
FILE: quality_control.py
======================================================================



======================================================================
FILE: fault_injection.py
======================================================================

In [31]:
import ast
import os

filepath = os.path.join(SRC_PATH, "quality_control.py")

with open(filepath, "r") as f:
    source = f.read()

tree = ast.parse(source)

print("Functions in quality_control.py:")

for node in ast.walk(tree):
    if isinstance(node, ast.FunctionDef):
        print(" -", node.name)
print(source)

Functions in quality_control.py:

In [32]:
filepath = os.path.join(SRC_PATH, "quality_control.py")

with open(filepath, "r") as f:
    source = f.read()

print(source)

In [33]:
qc_code = '''
import pandas as pd


# ============================================================
# Meteorological Quality Control Thresholds
# ============================================================

TEMP_MIN = -50.0
TEMP_MAX = 60.0

HUMIDITY_MIN = 0.0
HUMIDITY_MAX = 100.0

PRESSURE_MIN = 870.0
PRESSURE_MAX = 1085.0


# ============================================================
# Individual QC Rules
# ============================================================

def check_temperature(value):
    """
    Flag temperature values outside the broad physical
    plausibility range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < TEMP_MIN or value > TEMP_MAX)


def check_humidity(value):
    """
    Flag humidity values outside the physical range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < HUMIDITY_MIN or value > HUMIDITY_MAX)


def check_pressure(value):
    """
    Flag pressure values outside the broad physical
    plausibility range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < PRESSURE_MIN or value > PRESSURE_MAX)


# ============================================================
# Apply QC Rules to a DataFrame
# ============================================================

def apply_quality_control(df):
    """
    Apply basic meteorological QC rules to a weather DataFrame.

    Expected columns:
        temperature
        humidity
        pressure

    Adds:
        temperature_rule_flag
        humidity_rule_flag
        pressure_rule_flag
        qc_flag

    Returns:
        DataFrame with QC flags added.
    """

    df = df.copy()

    # Check required columns
    required_columns = [
        "temperature",
        "humidity",
        "pressure"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}"
        )

    # Apply individual rules
    df["temperature_rule_flag"] = (
        df["temperature"].apply(check_temperature)
    )

    df["humidity_rule_flag"] = (
        df["humidity"].apply(check_humidity)
    )

    df["pressure_rule_flag"] = (
        df["pressure"].apply(check_pressure)
    )

    # Overall QC flag
    df["qc_flag"] = (
        (df["temperature_rule_flag"] == 1)
        | (df["humidity_rule_flag"] == 1)
        | (df["pressure_rule_flag"] == 1)
    ).astype(int)

    return df
'''

QC_PATH = os.path.join(SRC_PATH, "quality_control.py")

with open(QC_PATH, "w") as f:
    f.write(qc_code)

print("quality_control.py created successfully!")
print(QC_PATH)

quality_control.py created successfully!
/content/SATARK_AI/src/quality_control.py

In [34]:
with open(QC_PATH, "r") as f:
    print(f.read())

import pandas as pd


# ============================================================
# Meteorological Quality Control Thresholds
# ============================================================

TEMP_MIN = -50.0
TEMP_MAX = 60.0

HUMIDITY_MIN = 0.0
HUMIDITY_MAX = 100.0

PRESSURE_MIN = 870.0
PRESSURE_MAX = 1085.0


# ============================================================
# Individual QC Rules
# ============================================================

def check_temperature(value):
    """
    Flag temperature values outside the broad physical
    plausibility range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < TEMP_MIN or value > TEMP_MAX)


def check_humidity(value):
    """
    Flag humidity values outside the physical range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < HUMIDITY_MIN or value > HUMIDITY_MAX)


def check_pressure(value):
    """
    Flag pressure values outside the broad physical
    plausibility range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < PRESSURE_MIN or value > PRESSURE_MAX)


# ============================================================
# Apply QC Rules to a DataFrame
# ============================================================

def apply_quality_control(df):
    """
    Apply basic meteorological QC rules to a weather DataFrame.

    Expected columns:
        temperature
        humidity
        pressure

    Adds:
        temperature_rule_flag
        humidity_rule_flag
        pressure_rule_flag
        qc_flag

    Returns:
        DataFrame with QC flags added.
    """

    df = df.copy()

    # Check required columns
    required_columns = [
        "temperature",
        "humidity",
        "pressure"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}"
        )

    # Apply individual rules
    df["temperature_rule_flag"] = (
        df["temperature"].apply(check_temperature)
    )

    df["humidity_rule_flag"] = (
        df["humidity"].apply(check_humidity)
    )

    df["pressure_rule_flag"] = (
        df["pressure"].apply(check_pressure)
    )

    # Overall QC flag
    df["qc_flag"] = (
        (df["temperature_rule_flag"] == 1)
        | (df["humidity_rule_flag"] == 1)
        | (df["pressure_rule_flag"] == 1)
    ).astype(int)

    return df

In [35]:
import sys

if SRC_PATH not in sys.path:
    sys.path.append(SRC_PATH)

from quality_control import apply_quality_control

In [36]:
df_qc_test = apply_quality_control(df_processed)

print("Original rows:", len(df_processed))
print("New rows:", len(df_qc_test))

display(
    df_qc_test[
        [
            "timestamp",
            "station_id",
            "temperature",
            "humidity",
            "pressure",
            "temperature_rule_flag",
            "humidity_rule_flag",
            "pressure_rule_flag",
            "qc_flag"
        ]
    ].head(10)
)

Original rows: 43100
New rows: 43100

,timestamp,station_id,temperature,humidity,pressure,temperature_rule_flag,humidity_rule_flag,pressure_rule_flag,qc_flag
0,2025-01-01 00:00:00,42131,5.4,97.0,1020.7,0,0,0,0
1,2025-01-01 01:00:00,42131,6.1,98.0,1019.5,0,0,0,0
2,2025-01-01 02:00:00,42131,6.1,94.0,1019.8,0,0,0,0
3,2025-01-01 03:00:00,42131,8.0,97.0,1021.5,0,0,0,0
4,2025-01-01 04:00:00,42131,7.6,96.0,1020.8,0,0,0,0
5,2025-01-01 05:00:00,42131,9.8,94.0,1021.0,0,0,0,0
6,2025-01-01 06:00:00,42131,10.0,92.0,1022.1,0,0,0,0
7,2025-01-01 07:00:00,42131,14.9,72.0,1019.7,0,0,0,0
8,2025-01-01 08:00:00,42131,16.3,65.0,1018.4,0,0,0,0
9,2025-01-01 09:00:00,42131,11.8,81.0,1019.1,0,0,0,0

In [37]:
print("Temperature flags:",
      df_qc_test["temperature_rule_flag"].sum())

print("Humidity flags:",
      df_qc_test["humidity_rule_flag"].sum())

print("Pressure flags:",
      df_qc_test["pressure_rule_flag"].sum())

print("Total QC flagged rows:",
      df_qc_test["qc_flag"].sum())

Temperature flags: 0
Humidity flags: 0
Pressure flags: 0
Total QC flagged rows: 0

In [38]:
test_data = pd.DataFrame({
    "temperature": [29.0, 55.0, 70.0, -60.0],
    "humidity": [50.0, 101.0, -5.0, 70.0],
    "pressure": [1012.0, 1100.0, 800.0, 1000.0]
})

test_result = apply_quality_control(test_data)

display(test_result)

,temperature,humidity,pressure,temperature_rule_flag,humidity_rule_flag,pressure_rule_flag,qc_flag
0,29.0,50.0,1012.0,0,0,0,0
1,55.0,101.0,1100.0,0,1,1,1
2,70.0,-5.0,800.0,1,1,1,1
3,-60.0,70.0,1000.0,1,0,0,1

In [40]:
FAULT_PATH = os.path.join(SRC_PATH, "fault_injection.py")

with open(FAULT_PATH, "r") as f:
    fault_source = f.read()

print(fault_source)

In [41]:
FAULT_PATH = os.path.join(SRC_PATH, "fault_injection.py")

print("Fault injection file:")
print(FAULT_PATH)

Fault injection file:
/content/SATARK_AI/src/fault_injection.py

In [42]:
spike_function = '''

def inject_temperature_spike(
    df,
    station_id,
    row_index,
    spike_value=55.0,
    severity="severe"
):
    """
    Inject a temperature spike into one observation.

    Parameters
    ----------
    df : pandas.DataFrame
        Input weather dataset.

    station_id : int
        Station where the fault should be injected.

    row_index : int
        Index of the row within the selected station.

    spike_value : float
        Temperature value to inject.

    severity : str
        Fault severity label.

    Returns
    -------
    pandas.DataFrame
        DataFrame with the injected temperature spike.
    """

    df = df.copy()

    # Check required columns
    required_columns = [
        "station_id",
        "temperature"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}"
        )

    # Select rows belonging to the requested station
    station_rows = df.index[
        df["station_id"] == station_id
    ].tolist()

    # Check station exists
    if not station_rows:
        raise ValueError(
            f"Station {station_id} was not found in the dataset."
        )

    # Check row_index is valid
    if row_index < 0 or row_index >= len(station_rows):
        raise IndexError(
            f"row_index must be between 0 and "
            f"{len(station_rows) - 1}."
        )

    # Get actual DataFrame index
    target_index = station_rows[row_index]

    # Preserve original temperature
    if "original_temperature" not in df.columns:
        df["original_temperature"] = df["temperature"]

    # Inject spike
    df.loc[target_index, "temperature"] = spike_value

    # Add/overwrite fault labels
    if "fault_type" not in df.columns:
        df["fault_type"] = "normal"

    if "fault_severity" not in df.columns:
        df["fault_severity"] = "none"

    if "is_anomaly" not in df.columns:
        df["is_anomaly"] = 0

    df.loc[target_index, "fault_type"] = "temperature_spike"
    df.loc[target_index, "fault_severity"] = severity
    df.loc[target_index, "is_anomaly"] = 1

    return df
'''

with open(FAULT_PATH, "w") as f:
    f.write(spike_function)

print("inject_temperature_spike() added successfully.")

inject_temperature_spike() added successfully.

In [43]:
import importlib
import fault_injection

importlib.reload(fault_injection)

from fault_injection import inject_temperature_spike

print("Function imported successfully!")

Function imported successfully!

In [44]:
print(
    df_processed[
        ["station_id", "station_name"]
    ].drop_duplicates().head(20)
)

       station_id station_name
0           42131       Hissar
8537        42139       Meerut
17061       42176       Rohtak
25578       42181        Palam
34339       42182   Safdarjung

In [45]:
TEST_STATION = df_processed["station_id"].iloc[0]

print("Test station:", TEST_STATION)

print(
    "Number of observations:",
    (df_processed["station_id"] == TEST_STATION).sum()
)

Test station: 42131
Number of observations: 8537

In [46]:
df_spike_test = inject_temperature_spike(
    df_processed,
    station_id=TEST_STATION,
    row_index=20,
    spike_value=55.0
)

print("Spike injection completed.")

Spike injection completed.

In [47]:
station_data = df_spike_test[
    df_spike_test["station_id"] == TEST_STATION
].reset_index(drop=True)

display(
    station_data.loc[
        15:25,
        [
            "timestamp",
            "station_id",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ]
)

,timestamp,station_id,temperature,original_temperature,fault_type,fault_severity,is_anomaly
15,2025-01-01 15:00:00,42131,9.2,9.2,normal,none,0
16,2025-01-01 16:00:00,42131,9.3,9.3,normal,none,0
17,2025-01-01 17:00:00,42131,8.8,8.8,normal,none,0
18,2025-01-01 18:00:00,42131,7.8,7.8,normal,none,0
19,2025-01-01 19:00:00,42131,7.4,7.4,normal,none,0
20,2025-01-01 20:00:00,42131,55.0,6.7,temperature_spike,severe,1
21,2025-01-01 21:00:00,42131,7.2,7.2,normal,none,0
22,2025-01-01 22:00:00,42131,7.0,7.0,normal,none,0
23,2025-01-01 23:00:00,42131,7.0,7.0,normal,none,0
24,2025-01-02 00:00:00,42131,6.2,6.2,normal,none,0
25,2025-01-02 01:00:00,42131,7.0,7.0,normal,none,0

In [48]:
missing_function = '''

def inject_missing(
    df,
    station_id,
    row_index,
    parameter="temperature",
    severity="moderate"
):
    """
    Inject a missing-value fault into one observation.

    The original value is preserved in the corresponding
    original_<parameter> column, while the observed value
    is replaced with NaN.

    Parameters
    ----------
    df : pandas.DataFrame
        Input weather dataset.

    station_id : int
        Station where the fault should be injected.

    row_index : int
        Row position within the selected station.

    parameter : str
        Weather parameter to make missing.
        Examples: temperature, humidity, pressure.

    severity : str
        Fault severity label.

    Returns
    -------
    pandas.DataFrame
        DataFrame with the injected missing value.
    """

    df = df.copy()

    # Check required columns
    if "station_id" not in df.columns:
        raise ValueError("Column 'station_id' is missing.")

    if parameter not in df.columns:
        raise ValueError(
            f"Parameter '{parameter}' is not present in the dataset."
        )

    # Find rows belonging to the selected station
    station_rows = df.index[
        df["station_id"] == station_id
    ].tolist()

    if not station_rows:
        raise ValueError(
            f"Station {station_id} was not found in the dataset."
        )

    # Check row position
    if row_index < 0 or row_index >= len(station_rows):
        raise IndexError(
            f"row_index must be between 0 and "
            f"{len(station_rows) - 1}."
        )

    target_index = station_rows[row_index]

    # Preserve original value
    original_column = f"original_{parameter}"

    if original_column not in df.columns:
        df[original_column] = df[parameter]

    # Inject missing value
    df.loc[target_index, parameter] = np.nan

    # Create fault columns if needed
    if "fault_type" not in df.columns:
        df["fault_type"] = "normal"

    if "fault_severity" not in df.columns:
        df["fault_severity"] = "none"

    if "is_anomaly" not in df.columns:
        df["is_anomaly"] = 0

    # Label fault
    df.loc[target_index, "fault_type"] = f"{parameter}_missing"
    df.loc[target_index, "fault_severity"] = severity
    df.loc[target_index, "is_anomaly"] = 1

    return df
'''

with open(FAULT_PATH, "a") as f:
    f.write(missing_function)

print("inject_missing() added successfully.")

inject_missing() added successfully.

In [52]:

with open(FAULT_PATH, "r") as f:
    content = f.read()

if "import numpy as np" not in content:
    content = "import numpy as np\n\n" + content

with open(FAULT_PATH, "w") as f:
    f.write(content)

print("NumPy import added successfully.")

NumPy import added successfully.

In [53]:
import importlib
import fault_injection

importlib.reload(fault_injection)

from fault_injection import (
    inject_temperature_spike,
    inject_missing
)

print("Both functions imported successfully!")

Both functions imported successfully!

In [54]:
df_missing_test = inject_missing(
    df_processed,
    station_id=TEST_STATION,
    row_index=30,
    parameter="temperature"
)

print("Missing-value injection completed.")

Missing-value injection completed.

In [55]:
station_data = df_missing_test[
    df_missing_test["station_id"] == TEST_STATION
].reset_index(drop=True)

display(
    station_data.loc[
        25:35,
        [
            "timestamp",
            "station_id",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ]
)

,timestamp,station_id,temperature,original_temperature,fault_type,fault_severity,is_anomaly
25,2025-01-02 01:00:00,42131,7.0,7.0,normal,none,0
26,2025-01-02 02:00:00,42131,7.2,7.2,normal,none,0
27,2025-01-02 03:00:00,42131,8.2,8.2,normal,none,0
28,2025-01-02 04:00:00,42131,9.4,9.4,normal,none,0
29,2025-01-02 05:00:00,42131,11.0,11.0,normal,none,0
30,2025-01-02 06:00:00,42131,NaN,10.0,temperature_missing,moderate,1
31,2025-01-02 07:00:00,42131,16.1,16.1,normal,none,0
32,2025-01-02 08:00:00,42131,17.4,17.4,normal,none,0
33,2025-01-02 09:00:00,42131,13.4,13.4,normal,none,0
34,2025-01-02 10:00:00,42131,18.0,18.0,normal,none,0
35,2025-01-02 11:00:00,42131,17.1,17.1,normal,none,0

In [56]:
frozen_function = '''

def inject_frozen(
    df,
    station_id,
    start_row,
    duration=6,
    parameter="temperature",
    severity="moderate"
):
    """
    Inject a frozen/stuck sensor fault over consecutive observations.

    The first value in the selected range is repeated for the
    remaining observations.

    Parameters
    ----------
    df : pandas.DataFrame
        Input weather dataset.

    station_id : int
        Station where the fault should be injected.

    start_row : int
        Starting row position within the selected station.

    duration : int
        Number of consecutive observations affected.

    parameter : str
        Weather parameter to freeze.

    severity : str
        Fault severity label.

    Returns
    -------
    pandas.DataFrame
        DataFrame with the frozen sensor fault.
    """

    df = df.copy()

    # Validate columns
    if "station_id" not in df.columns:
        raise ValueError("Column 'station_id' is missing.")

    if parameter not in df.columns:
        raise ValueError(
            f"Parameter '{parameter}' is not present in the dataset."
        )

    # Get station rows
    station_rows = df.index[
        df["station_id"] == station_id
    ].tolist()

    if not station_rows:
        raise ValueError(
            f"Station {station_id} was not found in the dataset."
        )

    # Validate duration
    if duration <= 0:
        raise ValueError("duration must be greater than 0.")

    # Validate start position
    if start_row < 0 or start_row >= len(station_rows):
        raise IndexError(
            f"start_row must be between 0 and "
            f"{len(station_rows) - 1}."
        )

    # Make sure the sequence fits
    end_row = start_row + duration

    if end_row > len(station_rows):
        raise IndexError(
            f"Not enough observations. "
            f"Only {len(station_rows) - start_row} observations "
            f"are available from start_row={start_row}."
        )

    # Preserve original values
    original_column = f"original_{parameter}"

    if original_column not in df.columns:
        df[original_column] = df[parameter]

    # Get the actual DataFrame indices
    target_indices = station_rows[start_row:end_row]

    # Use the first value as the frozen sensor value
    frozen_value = df.loc[target_indices[0], parameter]

    # Freeze the sensor
    df.loc[target_indices, parameter] = frozen_value

    # Create fault columns if needed
    if "fault_type" not in df.columns:
        df["fault_type"] = "normal"

    if "fault_severity" not in df.columns:
        df["fault_severity"] = "none"

    if "is_anomaly" not in df.columns:
        df["is_anomaly"] = 0

    # Label affected observations
    df.loc[target_indices, "fault_type"] = f"{parameter}_frozen"
    df.loc[target_indices, "fault_severity"] = severity
    df.loc[target_indices, "is_anomaly"] = 1

    return df
'''

with open(FAULT_PATH, "a") as f:
    f.write(frozen_function)

print("inject_frozen() added successfully.")

inject_frozen() added successfully.

In [57]:
import importlib
import fault_injection

importlib.reload(fault_injection)

from fault_injection import (
    inject_temperature_spike,
    inject_missing,
    inject_frozen
)

print("All three functions imported successfully!")

All three functions imported successfully!

In [58]:
df_frozen_test = inject_frozen(
    df_processed,
    station_id=TEST_STATION,
    start_row=40,
    duration=6,
    parameter="temperature"
)

print("Frozen sensor injection completed.")

Frozen sensor injection completed.

In [59]:
station_before = df_processed[
    df_processed["station_id"] == TEST_STATION
].reset_index(drop=True)

station_after = df_frozen_test[
    df_frozen_test["station_id"] == TEST_STATION
].reset_index(drop=True)

comparison = pd.DataFrame({
    "timestamp": station_before.loc[38:48, "timestamp"].values,
    "original_temperature": station_before.loc[
        38:48, "temperature"
    ].values,
    "new_temperature": station_after.loc[
        38:48, "temperature"
    ].values,
    "fault_type": station_after.loc[
        38:48, "fault_type"
    ].values,
    "is_anomaly": station_after.loc[
        38:48, "is_anomaly"
    ].values
})

display(comparison)

,timestamp,original_temperature,new_temperature,fault_type,is_anomaly
0,2025-01-02 14:00:00,12.5,12.5,normal,0
1,2025-01-02 15:00:00,10.0,10.0,normal,0
2,2025-01-02 16:00:00,10.4,10.4,temperature_frozen,1
3,2025-01-02 17:00:00,9.9,10.4,temperature_frozen,1
4,2025-01-02 18:00:00,7.8,10.4,temperature_frozen,1
5,2025-01-02 19:00:00,8.6,10.4,temperature_frozen,1
6,2025-01-02 20:00:00,8.4,10.4,temperature_frozen,1
7,2025-01-02 21:00:00,8.2,10.4,temperature_frozen,1
8,2025-01-02 22:00:00,7.3,7.3,normal,0
9,2025-01-02 23:00:00,6.9,6.9,normal,0
10,2025-01-03 00:00:00,6.2,6.2,normal,0

In [60]:
drift_function = '''

def inject_drift(
    df,
    station_id,
    start_row,
    duration=6,
    parameter="temperature",
    drift_per_step=1.0,
    severity="moderate"
):
    """
    Inject a gradual sensor drift over consecutive observations.

    Each subsequent reading is shifted further from the
    original value by drift_per_step.

    Parameters
    ----------
    df : pandas.DataFrame
        Input weather dataset.

    station_id : int
        Station where the drift should be injected.

    start_row : int
        Starting row position within the selected station.

    duration : int
        Number of consecutive observations affected.

    parameter : str
        Weather parameter to modify.

    drift_per_step : float
        Amount of additional drift applied at each step.

    severity : str
        Fault severity label.

    Returns
    -------
    pandas.DataFrame
        DataFrame with the injected drift.
    """

    df = df.copy()

    # Validate columns
    if "station_id" not in df.columns:
        raise ValueError("Column 'station_id' is missing.")

    if parameter not in df.columns:
        raise ValueError(
            f"Parameter '{parameter}' is not present in the dataset."
        )

    # Get station rows
    station_rows = df.index[
        df["station_id"] == station_id
    ].tolist()

    if not station_rows:
        raise ValueError(
            f"Station {station_id} was not found in the dataset."
        )

    # Validate duration
    if duration <= 0:
        raise ValueError("duration must be greater than 0.")

    if start_row < 0 or start_row >= len(station_rows):
        raise IndexError(
            f"start_row must be between 0 and "
            f"{len(station_rows) - 1}."
        )

    end_row = start_row + duration

    if end_row > len(station_rows):
        raise IndexError(
            f"Not enough observations for the requested duration."
        )

    # Preserve original values
    original_column = f"original_{parameter}"

    if original_column not in df.columns:
        df[original_column] = df[parameter]

    # Select target rows
    target_indices = station_rows[start_row:end_row]

    # Apply gradually increasing drift
    for step, idx in enumerate(target_indices):
        original_value = df.loc[idx, original_column]

        if pd.isna(original_value):
            continue

        df.loc[idx, parameter] = (
            original_value + (drift_per_step * step)
        )

    # Create fault columns if needed
    if "fault_type" not in df.columns:
        df["fault_type"] = "normal"

    if "fault_severity" not in df.columns:
        df["fault_severity"] = "none"

    if "is_anomaly" not in df.columns:
        df["is_anomaly"] = 0

    # Label affected rows
    df.loc[target_indices, "fault_type"] = f"{parameter}_drift"
    df.loc[target_indices, "fault_severity"] = severity
    df.loc[target_indices, "is_anomaly"] = 1

    return df
'''

with open(FAULT_PATH, "a") as f:
    f.write(drift_function)

print("inject_drift() added successfully.")

inject_drift() added successfully.

In [63]:
with open(FAULT_PATH, "r") as f:
    content = f.read()

if "import pandas as pd" not in content:
    content = "import pandas as pd\n" + content

with open(FAULT_PATH, "w") as f:
    f.write(content)

print("Pandas import added successfully.")

Pandas import added successfully.

In [64]:
import importlib
import fault_injection

importlib.reload(fault_injection)

from fault_injection import (
    inject_temperature_spike,
    inject_missing,
    inject_frozen,
    inject_drift
)

print("All four functions imported successfully!")

All four functions imported successfully!

In [65]:
df_drift_test = inject_drift(
    df_processed,
    station_id=TEST_STATION,
    start_row=60,
    duration=6,
    parameter="temperature",
    drift_per_step=1.0
)

print("Drift injection completed.")

Drift injection completed.

In [66]:
station_before = df_processed[
    df_processed["station_id"] == TEST_STATION
].reset_index(drop=True)

station_after = df_drift_test[
    df_drift_test["station_id"] == TEST_STATION
].reset_index(drop=True)

comparison = pd.DataFrame({
    "timestamp": station_before.loc[58:68, "timestamp"].values,
    "original_temperature": station_before.loc[
        58:68, "temperature"
    ].values,
    "new_temperature": station_after.loc[
        58:68, "temperature"
    ].values,
    "fault_type": station_after.loc[
        58:68, "fault_type"
    ].values,
    "is_anomaly": station_after.loc[
        58:68, "is_anomaly"
    ].values
})

display(comparison)

,timestamp,original_temperature,new_temperature,fault_type,is_anomaly
0,2025-01-03 10:00:00,19.8,19.8,normal,0
1,2025-01-03 11:00:00,18.9,18.9,normal,0
2,2025-01-03 12:00:00,13.4,13.4,temperature_drift,1
3,2025-01-03 13:00:00,14.2,15.2,temperature_drift,1
4,2025-01-03 14:00:00,12.8,14.8,temperature_drift,1
5,2025-01-03 15:00:00,10.4,13.4,temperature_drift,1
6,2025-01-03 16:00:00,10.3,14.3,temperature_drift,1
7,2025-01-03 17:00:00,9.7,14.7,temperature_drift,1
8,2025-01-03 18:00:00,8.0,8.0,normal,0
9,2025-01-03 19:00:00,8.8,8.8,normal,0
10,2025-01-03 20:00:00,8.5,8.5,normal,0

In [67]:
noise_function = '''

def inject_noise(
    df,
    station_id,
    start_row,
    duration=6,
    parameter="temperature",
    noise_std=2.0,
    random_state=42,
    severity="mild"
):
    """
    Inject random sensor noise over consecutive observations.

    Parameters
    ----------
    df : pandas.DataFrame
        Input weather dataset.

    station_id : int
        Station where the fault should be injected.

    start_row : int
        Starting row position within the selected station.

    duration : int
        Number of consecutive observations affected.

    parameter : str
        Weather parameter to modify.

    noise_std : float
        Standard deviation of the random noise.

    random_state : int
        Seed for reproducible noise.

    severity : str
        Fault severity label.

    Returns
    -------
    pandas.DataFrame
        DataFrame with injected sensor noise.
    """

    df = df.copy()

    # Validate columns
    if "station_id" not in df.columns:
        raise ValueError("Column 'station_id' is missing.")

    if parameter not in df.columns:
        raise ValueError(
            f"Parameter '{parameter}' is not present in the dataset."
        )

    # Get station rows
    station_rows = df.index[
        df["station_id"] == station_id
    ].tolist()

    if not station_rows:
        raise ValueError(
            f"Station {station_id} was not found in the dataset."
        )

    # Validate duration
    if duration <= 0:
        raise ValueError("duration must be greater than 0.")

    if start_row < 0 or start_row >= len(station_rows):
        raise IndexError(
            f"start_row must be between 0 and "
            f"{len(station_rows) - 1}."
        )

    end_row = start_row + duration

    if end_row > len(station_rows):
        raise IndexError(
            "Not enough observations for the requested duration."
        )

    # Preserve original values
    original_column = f"original_{parameter}"

    if original_column not in df.columns:
        df[original_column] = df[parameter]

    # Select target rows
    target_indices = station_rows[start_row:end_row]

    # Reproducible random generator
    rng = np.random.default_rng(random_state)

    # Apply random noise
    for idx in target_indices:

        original_value = df.loc[idx, original_column]

        if pd.isna(original_value):
            continue

        noise = rng.normal(
            loc=0.0,
            scale=noise_std
        )

        df.loc[idx, parameter] = original_value + noise

    # Create fault columns if needed
    if "fault_type" not in df.columns:
        df["fault_type"] = "normal"

    if "fault_severity" not in df.columns:
        df["fault_severity"] = "none"

    if "is_anomaly" not in df.columns:
        df["is_anomaly"] = 0

    # Label affected observations
    df.loc[target_indices, "fault_type"] = f"{parameter}_noise"
    df.loc[target_indices, "fault_severity"] = severity
    df.loc[target_indices, "is_anomaly"] = 1

    return df
'''

with open(FAULT_PATH, "a") as f:
    f.write(noise_function)

print("inject_noise() added successfully.")

inject_noise() added successfully.

In [68]:
import importlib
import fault_injection

importlib.reload(fault_injection)

from fault_injection import (
    inject_temperature_spike,
    inject_missing,
    inject_frozen,
    inject_drift,
    inject_noise
)

print("All five fault-injection functions imported successfully!")

All five fault-injection functions imported successfully!

In [69]:
df_noise_test = inject_noise(
    df_processed,
    station_id=TEST_STATION,
    start_row=80,
    duration=6,
    parameter="temperature",
    noise_std=2.0,
    random_state=42
)

print("Noise injection completed.")

Noise injection completed.

In [70]:
station_before = df_processed[
    df_processed["station_id"] == TEST_STATION
].reset_index(drop=True)

station_after = df_noise_test[
    df_noise_test["station_id"] == TEST_STATION
].reset_index(drop=True)

comparison = pd.DataFrame({
    "timestamp": station_before.loc[78:88, "timestamp"].values,
    "original_temperature": station_before.loc[
        78:88, "temperature"
    ].values,
    "new_temperature": station_after.loc[
        78:88, "temperature"
    ].values,
    "noise": (
        station_after.loc[
            78:88, "temperature"
        ].values
        -
        station_before.loc[
            78:88, "temperature"
        ].values
    ),
    "fault_type": station_after.loc[
        78:88, "fault_type"
    ].values,
    "is_anomaly": station_after.loc[
        78:88, "is_anomaly"
    ].values
})

display(comparison)

,timestamp,original_temperature,new_temperature,noise,fault_type,is_anomaly
0,2025-01-04 06:00:00,13.0,13.000000,0.000000,normal,0
1,2025-01-04 07:00:00,18.3,18.300000,0.000000,normal,0
2,2025-01-04 08:00:00,20.2,20.809434,0.609434,temperature_noise,1
3,2025-01-04 09:00:00,20.0,17.920032,-2.079968,temperature_noise,1
4,2025-01-04 10:00:00,21.8,23.300902,1.500902,temperature_noise,1
5,2025-01-04 11:00:00,20.4,22.281129,1.881129,temperature_noise,1
6,2025-01-04 12:00:00,17.6,13.697930,-3.902070,temperature_noise,1
7,2025-01-04 13:00:00,15.3,12.695641,-2.604359,temperature_noise,1
8,2025-01-04 14:00:00,14.9,14.900000,0.000000,normal,0
9,2025-01-04 15:00:00,13.6,13.600000,0.000000,normal,0
10,2025-01-04 16:00:00,14.0,14.000000,0.000000,normal,0

In [74]:
REPO_PATH = "/content/SATARK_AI"
SRC_PATH = os.path.join(REPO_PATH, "src")

QC_PATH = os.path.join(
    SRC_PATH,
    "quality_control.py"
)

print(QC_PATH)
print(os.path.exists(QC_PATH))

/content/SATARK_AI/src/quality_control.py
True

In [75]:
with open(QC_PATH, "r") as f:
    qc_code = f.read()

print(qc_code)

import pandas as pd


# ============================================================
# Meteorological Quality Control Thresholds
# ============================================================

TEMP_MIN = -50.0
TEMP_MAX = 60.0

HUMIDITY_MIN = 0.0
HUMIDITY_MAX = 100.0

PRESSURE_MIN = 870.0
PRESSURE_MAX = 1085.0


# ============================================================
# Individual QC Rules
# ============================================================

def check_temperature(value):
    """
    Flag temperature values outside the broad physical
    plausibility range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < TEMP_MIN or value > TEMP_MAX)


def check_humidity(value):
    """
    Flag humidity values outside the physical range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < HUMIDITY_MIN or value > HUMIDITY_MAX)


def check_pressure(value):
    """
    Flag pressure values outside the broad physical
    plausibility range.

    Returns:
        0 = normal
        1 = suspicious
    """
    if pd.isna(value):
        return 1

    return int(value < PRESSURE_MIN or value > PRESSURE_MAX)


# ============================================================
# Apply QC Rules to a DataFrame
# ============================================================

def apply_quality_control(df):
    """
    Apply basic meteorological QC rules to a weather DataFrame.

    Expected columns:
        temperature
        humidity
        pressure

    Adds:
        temperature_rule_flag
        humidity_rule_flag
        pressure_rule_flag
        qc_flag

    Returns:
        DataFrame with QC flags added.
    """

    df = df.copy()

    # Check required columns
    required_columns = [
        "temperature",
        "humidity",
        "pressure"
    ]

    missing_columns = [
        col for col in required_columns
        if col not in df.columns
    ]

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {missing_columns}"
        )

    # Apply individual rules
    df["temperature_rule_flag"] = (
        df["temperature"].apply(check_temperature)
    )

    df["humidity_rule_flag"] = (
        df["humidity"].apply(check_humidity)
    )

    df["pressure_rule_flag"] = (
        df["pressure"].apply(check_pressure)
    )

    # Overall QC flag
    df["qc_flag"] = (
        (df["temperature_rule_flag"] == 1)
        | (df["humidity_rule_flag"] == 1)
        | (df["pressure_rule_flag"] == 1)
    ).astype(int)

    return df

In [76]:
import sys
import os

if REPO_PATH not in sys.path:
    sys.path.append(REPO_PATH)

from src.quality_control import apply_quality_control

In [77]:
df_qc_test = apply_quality_control(df_processed)

print("QC applied successfully!")
print(df_qc_test.shape)

QC applied successfully!
(43100, 32)

In [78]:
print(df_qc_test.columns.tolist())

['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction', 'hour', 'day', 'month', 'day_of_week', 'day_of_year', 'time_period', 'temperature_rolling_mean_24h', 'temperature_rolling_std_24h', 'temperature_deviation_24h', 'temperature_zscore_24h', 'pressure_rolling_mean_24h', 'pressure_rolling_std_24h', 'pressure_deviation_24h', 'pressure_zscore_24h', 'humidity_rolling_mean_24h', 'humidity_rolling_std_24h', 'humidity_deviation_24h', 'humidity_zscore_24h', 'temperature_rule_flag', 'humidity_rule_flag', 'pressure_rule_flag', 'qc_flag']

In [79]:
print("Temperature flags:",
      df_qc_test["temperature_rule_flag"].sum())

print("Humidity flags:",
      df_qc_test["humidity_rule_flag"].sum())

print("Pressure flags:",
      df_qc_test["pressure_rule_flag"].sum())

print("Total QC flags:",
      df_qc_test["qc_flag"].sum())

Temperature flags: 0
Humidity flags: 0
Pressure flags: 0
Total QC flags: 0

In [80]:
qc_demo = pd.DataFrame({
    "temperature": [25.0, 75.0, -60.0],
    "humidity": [50.0, 110.0, -5.0],
    "pressure": [1013.0, 1100.0, 850.0]
})

qc_demo_result = apply_quality_control(qc_demo)

display(qc_demo_result)

,temperature,humidity,pressure,temperature_rule_flag,humidity_rule_flag,pressure_rule_flag,qc_flag
0,25.0,50.0,1013.0,0,0,0,0
1,75.0,110.0,1100.0,1,1,1,1
2,-60.0,-5.0,850.0,1,1,1,1

In [81]:
station_counts = (
    df_processed
    .groupby("station_id")
    .size()
    .sort_values(ascending=False)
)

display(station_counts.head(10))

station_id
42182    8761
42181    8761
42131    8537
42139    8524
42176    8517
dtype: int64

In [82]:
TEST_STATION = station_counts.index[0]

print("Selected demo station:", TEST_STATION)
print("Number of observations:", station_counts.iloc[0])

Selected demo station: 42182
Number of observations: 8761

In [83]:
station_demo = (
    df_processed[
        df_processed["station_id"] == TEST_STATION
    ]
    .sort_values("timestamp")
    .reset_index(drop=True)
)

print("Station:", TEST_STATION)
print("Rows:", len(station_demo))
print(
    "Time range:",
    station_demo["timestamp"].min(),
    "to",
    station_demo["timestamp"].max()
)

display(
    station_demo[
        ["timestamp", "station_id", "temperature",
         "humidity", "pressure"]
    ].head(10)
)

Station: 42182
Rows: 8761
Time range: 2025-01-01 00:00:00 to 2026-01-01 00:00:00

             timestamp  station_id  temperature  humidity  pressure
0  2025-01-01 00:00:00       42182         10.4      92.0    1019.2
1  2025-01-01 01:00:00       42182          8.4      94.0    1019.5
2  2025-01-01 02:00:00       42182          8.8      92.0    1019.7
3  2025-01-01 03:00:00       42182         10.0      87.0    1020.2
4  2025-01-01 04:00:00       42182         10.9      83.0    1020.2
5  2025-01-01 05:00:00       42182         11.7      80.0    1020.3
6  2025-01-01 06:00:00       42182         13.0      73.0    1020.9
7  2025-01-01 07:00:00       42182         14.0      70.0    1019.2
8  2025-01-01 08:00:00       42182         15.5      64.0    1018.2
9  2025-01-01 09:00:00       42182         14.8      70.0    1017.9

In [87]:
demo_spike = inject_temperature_spike(
    df_processed,
    station_id=TEST_STATION,
    row_index=100,
    spike_value=55.0,
    severity="severe"
)

print("Spike scenario created successfully.")

Spike scenario created successfully.

In [88]:
display(
    demo_spike[
        demo_spike["station_id"] == TEST_STATION
    ][
        [
            "timestamp",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ].iloc[95:106]
)

,timestamp,temperature,original_temperature,fault_type,fault_severity,is_anomaly
34434,2025-01-04 23:00:00,10.5,10.5,normal,none,0
34435,2025-01-05 00:00:00,10.0,10.0,normal,none,0
34436,2025-01-05 01:00:00,10.7,10.7,normal,none,0
34437,2025-01-05 02:00:00,10.9,10.9,normal,none,0
34438,2025-01-05 03:00:00,10.2,10.2,normal,none,0
34439,2025-01-05 04:00:00,55.0,11.4,temperature_spike,severe,1
34440,2025-01-05 05:00:00,12.7,12.7,normal,none,0
34441,2025-01-05 06:00:00,13.0,13.0,normal,none,0
34442,2025-01-05 07:00:00,15.3,15.3,normal,none,0
34443,2025-01-05 08:00:00,16.7,16.7,normal,none,0
34444,2025-01-05 09:00:00,17.2,17.2,normal,none,0

In [90]:
demo_missing = inject_missing(
    df_processed,
    station_id=TEST_STATION,
    row_index=200,
    parameter="temperature",
    severity="moderate"
)

print("Missing scenario created.")

Missing scenario created.

In [91]:
display(
    demo_missing[
        demo_missing["station_id"] == TEST_STATION
    ][
        [
            "timestamp",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ].iloc[195:206]
)

,timestamp,temperature,original_temperature,fault_type,fault_severity,is_anomaly
34534,2025-01-09 03:00:00,6.4,6.4,normal,none,0
34535,2025-01-09 04:00:00,9.5,9.5,normal,none,0
34536,2025-01-09 05:00:00,12.5,12.5,normal,none,0
34537,2025-01-09 06:00:00,19.0,19.0,normal,none,0
34538,2025-01-09 07:00:00,16.9,16.9,normal,none,0
34539,2025-01-09 08:00:00,NaN,18.2,temperature_missing,moderate,1
34540,2025-01-09 09:00:00,20.0,20.0,normal,none,0
34541,2025-01-09 10:00:00,19.3,19.3,normal,none,0
34542,2025-01-09 11:00:00,18.5,18.5,normal,none,0
34543,2025-01-09 12:00:00,17.0,17.0,normal,none,0
34544,2025-01-09 13:00:00,15.8,15.8,normal,none,0

In [92]:
demo_frozen = inject_frozen(
    df_processed,
    station_id=TEST_STATION,
    start_row=300,
    duration=6,
    parameter="temperature",
    severity="severe"
)

print("Frozen sensor scenario created.")

Frozen sensor scenario created.

In [93]:
display(
    demo_frozen[
        demo_frozen["station_id"] == TEST_STATION
    ][
        [
            "timestamp",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ].iloc[295:311]
)

,timestamp,temperature,original_temperature,fault_type,fault_severity,is_anomaly
34634,2025-01-13 07:00:00,15.0,15.0,normal,none,0
34635,2025-01-13 08:00:00,16.2,16.2,normal,none,0
34636,2025-01-13 09:00:00,18.0,18.0,normal,none,0
34637,2025-01-13 10:00:00,17.4,17.4,normal,none,0
34638,2025-01-13 11:00:00,16.9,16.9,normal,none,0
34639,2025-01-13 12:00:00,16.2,16.2,temperature_frozen,severe,1
34640,2025-01-13 13:00:00,16.2,15.3,temperature_frozen,severe,1
34641,2025-01-13 14:00:00,16.2,14.3,temperature_frozen,severe,1
34642,2025-01-13 15:00:00,16.2,14.0,temperature_frozen,severe,1
34643,2025-01-13 16:00:00,16.2,13.4,temperature_frozen,severe,1
34644,2025-01-13 17:00:00,16.2,12.8,temperature_frozen,severe,1
34645,2025-01-13 18:00:00,11.4,11.4,normal,none,0
34646,2025-01-13 19:00:00,11.9,11.9,normal,none,0
34647,2025-01-13 20:00:00,11.5,11.5,normal,none,0
34648,2025-01-13 21:00:00,10.6,10.6,normal,none,0
34649,2025-01-13 22:00:00,10.2,10.2,normal,none,0

In [94]:
demo_drift = inject_drift(
    df_processed,
    station_id=TEST_STATION,
    start_row=400,
    duration=6,
    parameter="temperature",
    drift_per_step=1.0,
    severity="moderate"
)

print("Drift scenario created.")

Drift scenario created.

In [95]:
display(
    demo_drift[
        demo_drift["station_id"] == TEST_STATION
    ][
        [
            "timestamp",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ].iloc[395:411]
)

,timestamp,temperature,original_temperature,fault_type,fault_severity,is_anomaly
34734,2025-01-17 11:00:00,16.7,16.7,normal,none,0
34735,2025-01-17 12:00:00,15.2,15.2,normal,none,0
34736,2025-01-17 13:00:00,15.1,15.1,normal,none,0
34737,2025-01-17 14:00:00,13.7,13.7,normal,none,0
34738,2025-01-17 15:00:00,11.4,11.4,normal,none,0
34739,2025-01-17 16:00:00,11.1,11.1,temperature_drift,moderate,1
34740,2025-01-17 17:00:00,11.9,10.9,temperature_drift,moderate,1
34741,2025-01-17 18:00:00,13.8,11.8,temperature_drift,moderate,1
34742,2025-01-17 19:00:00,13.2,10.2,temperature_drift,moderate,1
34743,2025-01-17 20:00:00,13.8,9.8,temperature_drift,moderate,1
34744,2025-01-17 21:00:00,16.6,11.6,temperature_drift,moderate,1
34745,2025-01-17 22:00:00,11.0,11.0,normal,none,0
34746,2025-01-17 23:00:00,10.5,10.5,normal,none,0
34747,2025-01-18 00:00:00,11.2,11.2,normal,none,0
34748,2025-01-18 01:00:00,10.0,10.0,normal,none,0
34749,2025-01-18 02:00:00,10.0,10.0,normal,none,0

In [96]:
demo_noise = inject_noise(
    df_processed,
    station_id=TEST_STATION,
    start_row=500,
    duration=6,
    parameter="temperature",
    noise_std=2.0,
    random_state=42,
    severity="mild"
)

print("Noise scenario created.")

Noise scenario created.

In [97]:
display(
    demo_noise[
        demo_noise["station_id"] == TEST_STATION
    ][
        [
            "timestamp",
            "temperature",
            "original_temperature",
            "fault_type",
            "fault_severity",
            "is_anomaly"
        ]
    ].iloc[495:511]
)

,timestamp,temperature,original_temperature,fault_type,fault_severity,is_anomaly
34834,2025-01-21 15:00:00,16.000000,16.0,normal,none,0
34835,2025-01-21 16:00:00,15.400000,15.4,normal,none,0
34836,2025-01-21 17:00:00,14.800000,14.8,normal,none,0
34837,2025-01-21 18:00:00,14.000000,14.0,normal,none,0
34838,2025-01-21 19:00:00,13.700000,13.7,normal,none,0
34839,2025-01-21 20:00:00,13.909434,13.3,temperature_noise,mild,1
34840,2025-01-21 21:00:00,8.720032,10.8,temperature_noise,mild,1
34841,2025-01-21 22:00:00,12.400902,10.9,temperature_noise,mild,1
34842,2025-01-21 23:00:00,12.781129,10.9,temperature_noise,mild,1
34843,2025-01-22 00:00:00,6.497930,10.4,temperature_noise,mild,1
34844,2025-01-22 01:00:00,8.395641,11.0,temperature_noise,mild,1
34845,2025-01-22 02:00:00,11.000000,11.0,normal,none,0
34846,2025-01-22 03:00:00,12.000000,12.0,normal,none,0
34847,2025-01-22 04:00:00,14.600000,14.6,normal,none,0
34848,2025-01-22 05:00:00,17.100000,17.1,normal,none,0
34849,2025-01-22 06:00:00,21.200000,21.2,normal,none,0

In [99]:
# Start from clean processed data
df_demo = df_processed.copy()

# -------------------------------------------------------
# 1. Temperature spike
# -------------------------------------------------------
df_demo = inject_temperature_spike(
    df_demo,
    station_id=TEST_STATION,
    row_index=100,
    spike_value=55.0,
    severity="severe"
)

# -------------------------------------------------------
# 2. Missing temperature
# -------------------------------------------------------
df_demo = inject_missing(
    df_demo,
    station_id=TEST_STATION,
    row_index=200,
    parameter="temperature",
    severity="moderate"
)

# -------------------------------------------------------
# 3. Frozen / stuck temperature sensor
# -------------------------------------------------------
df_demo = inject_frozen(
    df_demo,
    station_id=TEST_STATION,
    start_row=300,
    duration=6,
    parameter="temperature",
    severity="severe"
)

# -------------------------------------------------------
# 4. Temperature drift
# -------------------------------------------------------
df_demo = inject_drift(
    df_demo,
    station_id=TEST_STATION,
    start_row=400,
    duration=6,
    parameter="temperature",
    drift_per_step=1.0,
    severity="moderate"
)

# -------------------------------------------------------
# 5. Temperature noise
# -------------------------------------------------------
df_demo = inject_noise(
    df_demo,
    station_id=TEST_STATION,
    start_row=500,
    duration=6,
    parameter="temperature",
    noise_std=2.0,
    random_state=42,
    severity="mild"
)

print("Day 2 demo dataset created!")
print("Shape:", df_demo.shape)

Day 2 demo dataset created!
Shape: (43100, 32)

In [100]:
print("Shape:", df_demo.shape)
print(df_demo["fault_type"].value_counts())

Shape: (43100, 32)
fault_type
normal                 43080
temperature_frozen         6
temperature_noise          6
temperature_drift          6
temperature_spike          1
temperature_missing        1
Name: count, dtype: int64

In [101]:
print("Fault type distribution:")
print(df_demo["fault_type"].value_counts())

print("\nAnomaly count:")
print(df_demo["is_anomaly"].value_counts())

Fault type distribution:
fault_type
normal                 43080
temperature_frozen         6
temperature_noise          6
temperature_drift          6
temperature_spike          1
temperature_missing        1
Name: count, dtype: int64

Anomaly count:
is_anomaly
0    43080
1       20
Name: count, dtype: int64

In [102]:
fault_summary = (
    df_demo[
        df_demo["is_anomaly"] == 1
    ]
    .groupby(["fault_type", "fault_severity"])
    .size()
    .reset_index(name="count")
)

display(fault_summary)

            fault_type fault_severity  count
0    temperature_drift       moderate      6
1   temperature_frozen         severe      6
2  temperature_missing       moderate      1
3    temperature_noise           mild      6
4    temperature_spike         severe      1

In [103]:
demo_fault_rows = df_demo[
    df_demo["is_anomaly"] == 1
][
    [
        "timestamp",
        "station_id",
        "temperature",
        "original_temperature",
        "fault_type",
        "fault_severity",
        "is_anomaly"
    ]
]

display(demo_fault_rows)

,timestamp,station_id,temperature,original_temperature,fault_type,fault_severity,is_anomaly
34439,2025-01-05 04:00:00,42182,55.000000,11.4,temperature_spike,severe,1
34539,2025-01-09 08:00:00,42182,NaN,18.2,temperature_missing,moderate,1
34639,2025-01-13 12:00:00,42182,16.200000,16.2,temperature_frozen,severe,1
34640,2025-01-13 13:00:00,42182,16.200000,15.3,temperature_frozen,severe,1
34641,2025-01-13 14:00:00,42182,16.200000,14.3,temperature_frozen,severe,1
34642,2025-01-13 15:00:00,42182,16.200000,14.0,temperature_frozen,severe,1
34643,2025-01-13 16:00:00,42182,16.200000,13.4,temperature_frozen,severe,1
34644,2025-01-13 17:00:00,42182,16.200000,12.8,temperature_frozen,severe,1
34739,2025-01-17 16:00:00,42182,11.100000,11.1,temperature_drift,moderate,1
34740,2025-01-17 17:00:00,42182,11.900000,10.9,temperature_drift,moderate,1
34741,2025-01-17 18:00:00,42182,13.800000,11.8,temperature_drift,moderate,1
34742,2025-01-17 19:00:00,42182,13.200000,10.2,temperature_drift,moderate,1
34743,2025-01-17 20:00:00,42182,13.800000,9.8,temperature_drift,moderate,1
34744,2025-01-17 21:00:00,42182,16.600000,11.6,temperature_drift,moderate,1
34839,2025-01-21 20:00:00,42182,13.909434,13.3,temperature_noise,mild,1
34840,2025-01-21 21:00:00,42182,8.720032,10.8,temperature_noise,mild,1
34841,2025-01-21 22:00:00,42182,12.400902,10.9,temperature_noise,mild,1
34842,2025-01-21 23:00:00,42182,12.781129,10.9,temperature_noise,mild,1
34843,2025-01-22 00:00:00,42182,6.497930,10.4,temperature_noise,mild,1
34844,2025-01-22 01:00:00,42182,8.395641,11.0,temperature_noise,mild,1

In [104]:
from quality_control import apply_quality_control

In [105]:
df_demo_qc = apply_quality_control(df_demo)

print("QC applied successfully!")

QC applied successfully!

In [106]:
qc_columns = [
    "temperature_rule_flag",
    "humidity_rule_flag",
    "pressure_rule_flag",
    "qc_flag"
]

display(df_demo_qc[qc_columns].head())

   temperature_rule_flag  humidity_rule_flag  pressure_rule_flag  qc_flag
0                      0                   0                   0        0
1                      0                   0                   0        0
2                      0                   0                   0        0
3                      0                   0                   0        0
4                      0                   0                   0        0

In [107]:
print("QC flag totals:")
print(df_demo_qc[qc_columns].sum())

QC flag totals:
temperature_rule_flag    1
humidity_rule_flag       0
pressure_rule_flag       0
qc_flag                  1
dtype: int64

In [108]:
DRIVE_SYNTHETIC_PATH = "/content/drive/MyDrive/SATARK_AI/data/synthetic"

print(os.path.exists(DRIVE_SYNTHETIC_PATH))

True

In [109]:
DEMO_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "day2_demo_faults.csv"
)

df_demo_qc.to_csv(
    DEMO_OUTPUT_PATH,
    index=False
)

print("Saved successfully!")
print(DEMO_OUTPUT_PATH)

Saved successfully!
/content/drive/MyDrive/SATARK_AI/data/synthetic/day2_demo_faults.csv

In [110]:
df_check = pd.read_csv(DEMO_OUTPUT_PATH)

print("Reloaded successfully!")
print("Shape:", df_check.shape)

print("\nFault distribution:")
print(df_check["fault_type"].value_counts())

print("\nAnomaly distribution:")
print(df_check["is_anomaly"].value_counts())

Reloaded successfully!
Shape: (43100, 36)

Fault distribution:
fault_type
normal                 43080
temperature_frozen         6
temperature_noise          6
temperature_drift          6
temperature_spike          1
temperature_missing        1
Name: count, dtype: int64

Anomaly distribution:
is_anomaly
0    43080
1       20
Name: count, dtype: int64

In [111]:
print("Final dataset columns:")
for i, col in enumerate(df_demo_qc.columns, start=1):
    print(f"{i}. {col}")

Final dataset columns:
1. timestamp
2. station_id
3. station_name
4. latitude
5. longitude
6. temperature
7. humidity
8. pressure
9. wind_speed
10. wind_direction
11. hour
12. day
13. month
14. day_of_week
15. day_of_year
16. time_period
17. temperature_rolling_mean_24h
18. temperature_rolling_std_24h
19. temperature_deviation_24h
20. temperature_zscore_24h
21. pressure_rolling_mean_24h
22. pressure_rolling_std_24h
23. pressure_deviation_24h
24. pressure_zscore_24h
25. humidity_rolling_mean_24h
26. humidity_rolling_std_24h
27. humidity_deviation_24h
28. humidity_zscore_24h
29. original_temperature
30. fault_type
31. fault_severity
32. is_anomaly
33. temperature_rule_flag
34. humidity_rule_flag
35. pressure_rule_flag
36. qc_flag

In [112]:
print("Number of columns:", len(df_demo_qc.columns))
print("Number of rows:", len(df_demo_qc))

Number of columns: 36
Number of rows: 43100

In [113]:
required_for_person2 = [
    "timestamp",
    "station_id",
    "station_name",
    "latitude",
    "longitude",
    "temperature",
    "humidity",
    "pressure",
    "temperature_rolling_mean_24h",
    "temperature_rolling_std_24h",
    "temperature_deviation_24h",
    "temperature_zscore_24h",
    "pressure_rolling_mean_24h",
    "pressure_rolling_std_24h",
    "pressure_deviation_24h",
    "pressure_zscore_24h",
    "humidity_rolling_mean_24h",
    "humidity_rolling_std_24h",
    "humidity_deviation_24h",
    "humidity_zscore_24h",
    "original_temperature",
    "original_pressure",
    "original_humidity",
    "fault_type",
    "fault_severity",
    "is_anomaly",
    "temperature_rule_flag",
    "humidity_rule_flag",
    "pressure_rule_flag",
    "qc_flag"
]

missing_for_person2 = [
    col for col in required_for_person2
    if col not in df_demo_qc.columns
]

if missing_for_person2:
    print("Missing columns:")
    print(missing_for_person2)
else:
    print("All required Person 2 columns are present! ✅")

Missing columns:
['original_pressure', 'original_humidity']

In [118]:
df_demo_qc["original_humidity"] = df_demo_qc["humidity"]
df_demo_qc["original_pressure"] = df_demo_qc["pressure"]

print("Added original_humidity and original_pressure.")

print(
    df_demo_qc[
        [
            "humidity",
            "original_humidity",
            "pressure",
            "original_pressure"
        ]
    ].head()
)

Added original_humidity and original_pressure.
   humidity  original_humidity  pressure  original_pressure
0      97.0               97.0    1020.7             1020.7
1      98.0               98.0    1019.5             1019.5
2      94.0               94.0    1019.8             1019.8
3      97.0               97.0    1021.5             1021.5
4      96.0               96.0    1020.8             1020.8

In [123]:
DEMO_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "demo_faults.csv"
)

df_demo_qc.to_csv(
    DEMO_OUTPUT_PATH,
    index=False
)
print(DEMO_OUTPUT_PATH)

/content/drive/MyDrive/SATARK_AI/data/synthetic/demo_faults.csv

In [124]:
df_check = pd.read_csv(DEMO_OUTPUT_PATH)

print("Reloaded successfully!")
print("Shape:", df_check.shape)

print("\nFault distribution:")
print(df_check["fault_type"].value_counts())

print("\nAnomaly distribution:")
print(df_check["is_anomaly"].value_counts())

print("\nRequired original columns:")
print(
    df_check[
        [
            "original_temperature",
            "original_humidity",
            "original_pressure"
        ]
    ].head()
)

Reloaded successfully!
Shape: (43100, 38)

Fault distribution:
fault_type
normal                 43080
temperature_frozen         6
temperature_noise          6
temperature_drift          6
temperature_spike          1
temperature_missing        1
Name: count, dtype: int64

Anomaly distribution:
is_anomaly
0    43080
1       20
Name: count, dtype: int64

Required original columns:
   original_temperature  original_humidity  original_pressure
0                   5.4               97.0             1020.7
1                   6.1               98.0             1019.5
2                   6.1               94.0             1019.8
3                   8.0               97.0             1021.5
4                   7.6               96.0             1020.8

In [125]:
# ============================================================
# PERSON 2 HANDOFF DATASET
# ============================================================

person2_columns = [
    "timestamp",
    "station_id",
    "station_name",
    "temperature",
    "original_temperature",
    "humidity",
    "original_humidity",
    "pressure",
    "original_pressure",
    "wind_speed",
    "wind_direction",

    # Time features
    "hour",
    "day",
    "month",
    "day_of_week",
    "day_of_year",
    "time_period",

    # Rolling/statistical features
    "temperature_rolling_mean_24h",
    "temperature_rolling_std_24h",
    "temperature_deviation_24h",
    "temperature_zscore_24h",

    "pressure_rolling_mean_24h",
    "pressure_rolling_std_24h",
    "pressure_deviation_24h",
    "pressure_zscore_24h",

    "humidity_rolling_mean_24h",
    "humidity_rolling_std_24h",
    "humidity_deviation_24h",
    "humidity_zscore_24h",

    # Ground truth
    "fault_type",
    "fault_severity",
    "is_anomaly",

    # QC
    "temperature_rule_flag",
    "humidity_rule_flag",
    "pressure_rule_flag",
    "qc_flag"
]

missing_columns = [
    col for col in person2_columns
    if col not in df_demo_qc.columns
]

if missing_columns:
    print("Missing columns:")
    print(missing_columns)
else:
    df_person2 = df_demo_qc[person2_columns].copy()

    print("Person 2 handoff dataset created! ✅")
    print("Rows:", len(df_person2))
    print("Columns:", len(df_person2.columns))

Person 2 handoff dataset created! ✅
Rows: 43100
Columns: 36

In [128]:
PERSON2_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "p2_day2_handoff.csv"
)

df_person2.to_csv(
    PERSON2_OUTPUT_PATH,
    index=False
)

print("P2 handoff saved successfully! ✅")
print(PERSON2_OUTPUT_PATH)

P2 handoff saved successfully! ✅
/content/drive/MyDrive/SATARK_AI/data/synthetic/p2_day2_handoff.csv

In [129]:
import os
import shutil

# Drive destination
DRIVE_SYNTHETIC_PATH = "/content/drive/MyDrive/SATARK_AI/data/synthetic"

# Create folder if it doesn't exist
os.makedirs(DRIVE_SYNTHETIC_PATH, exist_ok=True)

print("Drive folder:", DRIVE_SYNTHETIC_PATH)
print("Folder exists:", os.path.exists(DRIVE_SYNTHETIC_PATH))

Drive folder: /content/drive/MyDrive/SATARK_AI/data/synthetic
Folder exists: True

In [130]:
PROCESSED_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "processed_meteostat_data.csv"
)

df_processed.to_csv(
    PROCESSED_OUTPUT_PATH,
    index=False
)

print("Saved:", PROCESSED_OUTPUT_PATH)

Saved: /content/drive/MyDrive/SATARK_AI/data/synthetic/processed_meteostat_data.csv

In [131]:
SYNTHETIC_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "synthetic_fault_data.csv"
)

df_synthetic.to_csv(
    SYNTHETIC_OUTPUT_PATH,
    index=False
)

print("Saved:", SYNTHETIC_OUTPUT_PATH)

Saved: /content/drive/MyDrive/SATARK_AI/data/synthetic/synthetic_fault_data.csv

In [133]:
DEMO_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "demo_faults.csv"
)

df_demo_qc.to_csv(
    DEMO_OUTPUT_PATH,
    index=False
)

print("Saved:", DEMO_OUTPUT_PATH)

Saved: /content/drive/MyDrive/SATARK_AI/data/synthetic/demo_faults.csv

In [135]:
P2_OUTPUT_PATH = os.path.join(
    DRIVE_SYNTHETIC_PATH,
    "p2_day2_handoff.csv"
)

df_person2.to_csv(
    P2_OUTPUT_PATH,
    index=False
)

print("Saved:", P2_OUTPUT_PATH)

Saved: /content/drive/MyDrive/SATARK_AI/data/synthetic/p2_day2_handoff.csv

In [136]:

files_to_check = [
    "processed_meteostat_data.csv",
    "synthetic_fault_data.csv",
    "day2_demo_faults.csv",
    "person2_day2_handoff.csv"
]

print("========== DRIVE FILE CHECK ==========\n")

for filename in files_to_check:
    path = os.path.join(DRIVE_SYNTHETIC_PATH, filename)

    if os.path.exists(path):
        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"✅ {filename} — {size_mb:.2f} MB")
    else:
        print(f"❌ {filename} — NOT FOUND")

print("\nLocation:")
print(DRIVE_SYNTHETIC_PATH)

========== DRIVE FILE CHECK ==========

✅ processed_meteostat_data.csv — 12.58 MB
✅ synthetic_fault_data.csv — 13.84 MB
✅ day2_demo_faults.csv — 14.18 MB
✅ person2_day2_handoff.csv — 13.54 MB

Location:
/content/drive/MyDrive/SATARK_AI/data/synthetic

In [137]:
# ============================================================
# COPY PERSON 1 PYTHON FILES TO GOOGLE DRIVE
# ============================================================

import os
import shutil

# GitHub project folder in Colab
GITHUB_SRC_PATH = "/content/SATARK_AI/src"

# Google Drive destination
DRIVE_SRC_PATH = "/content/drive/MyDrive/SATARK_AI/src"

# Create Drive src folder
os.makedirs(DRIVE_SRC_PATH, exist_ok=True)

# Person 1 files
person1_files = [
    "data_preprocessing.py",
    "quality_control.py",
    "fault_injection.py"
]

# Copy files
for filename in person1_files:

    source = os.path.join(GITHUB_SRC_PATH, filename)
    destination = os.path.join(DRIVE_SRC_PATH, filename)

    if os.path.exists(source):
        shutil.copy2(source, destination)
        print(f"✅ Copied: {filename}")
    else:
        print(f"❌ Not found in GitHub folder: {filename}")

print("\nPerson 1 .py files copied to Google Drive!")
print("Location:", DRIVE_SRC_PATH)

✅ Copied: data_preprocessing.py
✅ Copied: quality_control.py
✅ Copied: fault_injection.py

Person 1 .py files copied to Google Drive!
Location: /content/drive/MyDrive/SATARK_AI/src

In [139]:
print("========== DRIVE SRC CHECK ==========\n")

for filename in person1_files:

    path = os.path.join(DRIVE_SRC_PATH, filename)

    if os.path.exists(path):
        size_kb = os.path.getsize(path) / 1024
        print(f"✅ {filename} — {size_kb:.2f} KB")
    else:
        print(f"❌ {filename} — NOT FOUND")

========== DRIVE SRC CHECK ==========

✅ data_preprocessing.py — 0.00 KB
✅ quality_control.py — 2.59 KB
✅ fault_injection.py — 13.09 KB