<a href="https://colab.research.google.com/github/anushah-200/SATARK_AI/blob/main/notebooks/P3_spatial_diagnosis_integration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/anushah-200/SATARK_AI

Cloning into 'SATARK_AI'...
remote: Enumerating objects: 145, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (125/125), done.
remote: Total 145 (delta 58), reused 26 (delta 6), pack-reused 0 (from 0)
Receiving objects: 100% (145/145), 8.06 MiB | 6.09 MiB/s, done.
Resolving deltas: 100% (58/58), done.

In [ ]:
%cd SATARK_AI

/content/SATARK_AI

In [ ]:
!ls

dashboard  docs     notebooks  README.md	 src
data	   LICENSE  outputs    requirements.txt  tests

In [ ]:
!find src -maxdepth 2 -type f

src/fault_injection.py
src/__init__.py
src/quality_control.py
src/data_preprocessing.py
src/anomaly_detection.py
src/sensor_health.py
src/diagnosis.py
src/anomaly_detector.py
src/spatial_analysis.py
src/evaluate_model.py

In [ ]:
!find data -maxdepth 2 -type f

data/synthetic/synthetic_fault_data.csv
data/raw/meteostat_data.csv
data/processed/processed_meteostat_data.csv

In [ ]:
!find outputs -maxdepth 2 -type f

outputs/results/anomaly_detection_results.csv

In [ ]:
!ls /content/drive/MyDrive/SATARK_AI/

data  models  notebooks  outputs  src

In [ ]:
!find "/content/drive/MyDrive/SATARK_AI" -type f

/content/drive/MyDrive/SATARK_AI/data/processed/processed_meteostat_data.csv
/content/drive/MyDrive/SATARK_AI/data/raw/meteostat_data.csv
/content/drive/MyDrive/SATARK_AI/data/synthetic/synthetic_fault_data.csv

In [ ]:
import pandas as pd
synthetic_path="/content/drive/MyDrive/SATARK_AI/data/synthetic/synthetic_fault_data.csv"
df=pd.read_csv(synthetic_path)
print("Shape:",df.shape)
print("\nColumns")
print(df.columns.tolist())

display(df.head())

Shape: (43100, 34)

Columns
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction', 'hour', 'day', 'month', 'day_of_week', 'day_of_year', 'time_period', 'temperature_rolling_mean_24h', 'temperature_rolling_std_24h', 'temperature_deviation_24h', 'temperature_zscore_24h', 'pressure_rolling_mean_24h', 'pressure_rolling_std_24h', 'pressure_deviation_24h', 'pressure_zscore_24h', 'humidity_rolling_mean_24h', 'humidity_rolling_std_24h', 'humidity_deviation_24h', 'humidity_zscore_24h', 'original_temperature', 'original_pressure', 'original_humidity', 'is_anomaly', 'fault_type', 'fault_severity']

,timestamp,station_id,station_name,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction,...,humidity_rolling_mean_24h,humidity_rolling_std_24h,humidity_deviation_24h,humidity_zscore_24h,original_temperature,original_pressure,original_humidity,is_anomaly,fault_type,fault_severity
0,2025-01-01 00:00:00,42131,Hissar,29.1667,75.7333,5.4,97.0,1020.7,0.0,0.0,...,NaN,NaN,NaN,NaN,5.4,1020.7,97.0,0,normal,none
1,2025-01-01 01:00:00,42131,Hissar,29.1667,75.7333,6.1,98.0,1019.5,5.0,283.0,...,NaN,NaN,NaN,NaN,6.1,1019.5,98.0,0,normal,none
2,2025-01-01 02:00:00,42131,Hissar,29.1667,75.7333,6.1,94.0,1019.8,5.4,274.0,...,NaN,NaN,NaN,NaN,6.1,1019.8,94.0,0,normal,none
3,2025-01-01 03:00:00,42131,Hissar,29.1667,75.7333,8.0,97.0,1021.5,0.0,0.0,...,96.333333,2.081666,0.666667,0.320256,8.0,1021.5,97.0,0,normal,none
4,2025-01-01 04:00:00,42131,Hissar,29.1667,75.7333,7.6,96.0,1020.8,6.8,276.0,...,96.500000,1.732051,-0.500000,-0.288675,7.6,1020.8,96.0,0,normal,none

In [ ]:
raw_path = "/content/drive/MyDrive/SATARK_AI/data/raw/meteostat_data.csv"
processed_path = "/content/drive/MyDrive/SATARK_AI/data/processed/processed_meteostat_data.csv"

raw_df = pd.read_csv(raw_path)
processed_df = pd.read_csv(processed_path)

print("RAW DATA")
print(raw_df.shape)
print(raw_df.columns.tolist())

print("\nPROCESSED DATA")
print(processed_df.shape)
print(processed_df.columns.tolist())

RAW DATA
(43100, 10)
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction']

PROCESSED DATA
(43100, 28)
['timestamp', 'station_id', 'station_name', 'latitude', 'longitude', 'temperature', 'humidity', 'pressure', 'wind_speed', 'wind_direction', 'hour', 'day', 'month', 'day_of_week', 'day_of_year', 'time_period', 'temperature_rolling_mean_24h', 'temperature_rolling_std_24h', 'temperature_deviation_24h', 'temperature_zscore_24h', 'pressure_rolling_mean_24h', 'pressure_rolling_std_24h', 'pressure_deviation_24h', 'pressure_zscore_24h', 'humidity_rolling_mean_24h', 'humidity_rolling_std_24h', 'humidity_deviation_24h', 'humidity_zscore_24h']

In [ ]:
print("SYNTHETIC DATA")
print(df.info())

print("\nFIRST 10 ROWS")
display(df.head(10))

SYNTHETIC DATA
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43100 entries, 0 to 43099
Data columns (total 34 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   timestamp                     43100 non-null  object
 1   station_id                    43100 non-null  int64
 2   station_name                  43100 non-null  object
 3   latitude                      43100 non-null  float64
 4   longitude                     43100 non-null  float64
 5   temperature                   43074 non-null  float64
 6   humidity                      43091 non-null  float64
 7   pressure                      43074 non-null  float64
 8   wind_speed                    43100 non-null  float64
 9   wind_direction                42950 non-null  float64
 10  hour                          43100 non-null  int64
 11  day                           43100 non-null  int64
 12  month                         43100 non-null  int64
 13  day_of_week                   43100 non-null  int64
 14  day_of_year                   43100 non-null  int64
 15  time_period                   43100 non-null  object
 16  temperature_rolling_mean_24h  43085 non-null  float64
 17  temperature_rolling_std_24h   43085 non-null  float64
 18  temperature_deviation_24h     43085 non-null  float64
 19  temperature_zscore_24h        43085 non-null  float64
 20  pressure_rolling_mean_24h     43085 non-null  float64
 21  pressure_rolling_std_24h      43085 non-null  float64
 22  pressure_deviation_24h        43085 non-null  float64
 23  pressure_zscore_24h           43085 non-null  float64
 24  humidity_rolling_mean_24h     43085 non-null  float64
 25  humidity_rolling_std_24h      43085 non-null  float64
 26  humidity_deviation_24h        43085 non-null  float64
 27  humidity_zscore_24h           43084 non-null  float64
 28  original_temperature          43100 non-null  float64
 29  original_pressure             43100 non-null  float64
 30  original_humidity             43100 non-null  float64
 31  is_anomaly                    43100 non-null  int64
 32  fault_type                    43100 non-null  object
 33  fault_severity                43100 non-null  object
dtypes: float64(22), int64(7), object(5)
memory usage: 11.2+ MB
None

FIRST 10 ROWS

,timestamp,station_id,station_name,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction,...,humidity_rolling_mean_24h,humidity_rolling_std_24h,humidity_deviation_24h,humidity_zscore_24h,original_temperature,original_pressure,original_humidity,is_anomaly,fault_type,fault_severity
0,2025-01-01 00:00:00,42131,Hissar,29.1667,75.7333,5.4,97.0,1020.7,0.0,0.0,...,NaN,NaN,NaN,NaN,5.4,1020.7,97.0,0,normal,none
1,2025-01-01 01:00:00,42131,Hissar,29.1667,75.7333,6.1,98.0,1019.5,5.0,283.0,...,NaN,NaN,NaN,NaN,6.1,1019.5,98.0,0,normal,none
2,2025-01-01 02:00:00,42131,Hissar,29.1667,75.7333,6.1,94.0,1019.8,5.4,274.0,...,NaN,NaN,NaN,NaN,6.1,1019.8,94.0,0,normal,none
3,2025-01-01 03:00:00,42131,Hissar,29.1667,75.7333,8.0,97.0,1021.5,0.0,0.0,...,96.333333,2.081666,0.666667,0.320256,8.0,1021.5,97.0,0,normal,none
4,2025-01-01 04:00:00,42131,Hissar,29.1667,75.7333,7.6,96.0,1020.8,6.8,276.0,...,96.500000,1.732051,-0.500000,-0.288675,7.6,1020.8,96.0,0,normal,none
5,2025-01-01 05:00:00,42131,Hissar,29.1667,75.7333,9.8,94.0,1021.0,6.5,292.0,...,96.400000,1.516575,-2.400000,-1.582513,9.8,1021.0,94.0,0,normal,none
6,2025-01-01 06:00:00,42131,Hissar,29.1667,75.7333,10.0,92.0,1022.1,3.6,320.0,...,96.000000,1.673320,-4.000000,-2.390457,10.0,1022.1,92.0,0,normal,none
7,2025-01-01 07:00:00,42131,Hissar,29.1667,75.7333,14.9,72.0,1019.7,6.8,289.0,...,95.428571,2.149197,-23.428571,-10.901082,14.9,1019.7,72.0,0,normal,none
8,2025-01-01 08:00:00,42131,Hissar,29.1667,75.7333,16.3,65.0,1018.4,7.9,291.0,...,92.500000,8.518887,-27.500000,-3.228121,16.3,1018.4,65.0,0,normal,none
9,2025-01-01 09:00:00,42131,Hissar,29.1667,75.7333,11.8,81.0,1019.1,3.6,320.0,...,89.444444,12.146101,-8.444444,-0.695239,11.8,1019.1,81.0,0,normal,none

In [ ]:
print("\nCOLUMN NAMES:")
for i, col in enumerate(df.columns):
    print(i, repr(col))

COLUMN NAMES:
0 'timestamp'
1 'station_id'
2 'station_name'
3 'latitude'
4 'longitude'
5 'temperature'
6 'humidity'
7 'pressure'
8 'wind_speed'
9 'wind_direction'
10 'hour'
11 'day'
12 'month'
13 'day_of_week'
14 'day_of_year'
15 'time_period'
16 'temperature_rolling_mean_24h'
17 'temperature_rolling_std_24h'
18 'temperature_deviation_24h'
19 'temperature_zscore_24h'
20 'pressure_rolling_mean_24h'
21 'pressure_rolling_std_24h'
22 'pressure_deviation_24h'
23 'pressure_zscore_24h'
24 'humidity_rolling_mean_24h'
25 'humidity_rolling_std_24h'
26 'humidity_deviation_24h'
27 'humidity_zscore_24h'
28 'original_temperature'
29 'original_pressure'
30 'original_humidity'
31 'is_anomaly'
32 'fault_type'
33 'fault_severity'

In [ ]:
print(df["station_id"].unique())

[42131 42139 42176 42181 42182]

In [ ]:
print("Number of stations:", df["station_id"].nunique())

Number of stations: 5

In [ ]:
import pandas as pd
import numpy as np

DATA_PATH = "/content/drive/MyDrive/SATARK_AI/data/synthetic/synthetic_fault_data.csv"

df = pd.read_csv(DATA_PATH)

df["timestamp"] = pd.to_datetime(df["timestamp"])

print("Shape:", df.shape)
display(df.head())

Shape: (43100, 34)

,timestamp,station_id,station_name,latitude,longitude,temperature,humidity,pressure,wind_speed,wind_direction,...,humidity_rolling_mean_24h,humidity_rolling_std_24h,humidity_deviation_24h,humidity_zscore_24h,original_temperature,original_pressure,original_humidity,is_anomaly,fault_type,fault_severity
0,2025-01-01 00:00:00,42131,Hissar,29.1667,75.7333,5.4,97.0,1020.7,0.0,0.0,...,NaN,NaN,NaN,NaN,5.4,1020.7,97.0,0,normal,none
1,2025-01-01 01:00:00,42131,Hissar,29.1667,75.7333,6.1,98.0,1019.5,5.0,283.0,...,NaN,NaN,NaN,NaN,6.1,1019.5,98.0,0,normal,none
2,2025-01-01 02:00:00,42131,Hissar,29.1667,75.7333,6.1,94.0,1019.8,5.4,274.0,...,NaN,NaN,NaN,NaN,6.1,1019.8,94.0,0,normal,none
3,2025-01-01 03:00:00,42131,Hissar,29.1667,75.7333,8.0,97.0,1021.5,0.0,0.0,...,96.333333,2.081666,0.666667,0.320256,8.0,1021.5,97.0,0,normal,none
4,2025-01-01 04:00:00,42131,Hissar,29.1667,75.7333,7.6,96.0,1020.8,6.8,276.0,...,96.500000,1.732051,-0.500000,-0.288675,7.6,1020.8,96.0,0,normal,none

In [ ]:
print(df["station_id"].unique())

[42131 42139 42176 42181 42182]

In [ ]:
stations = (
    df[["station_id", "station_name", "latitude", "longitude"]]
    .drop_duplicates("station_id")
    .reset_index(drop=True)
)

display(stations)

   station_id station_name  latitude  longitude
0       42131       Hissar   29.1667    75.7333
1       42139       Meerut   29.0167    77.6333
2       42176       Rohtak   28.8333    76.5833
3       42181        Palam   28.5667    77.1167
4       42182   Safdarjung   28.5833    77.2000

In [ ]:
from math import radians, sin, cos, sqrt, atan2

def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate distance between two coordinates in kilometers.
    """

    R = 6371.0  # Earth radius in km

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2) ** 2
        + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    return R * c

In [ ]:
def create_distance_matrix(stations):
    station_ids = stations["station_id"].tolist()

    distance_matrix = pd.DataFrame(
        index=station_ids,
        columns=station_ids,
        dtype=float
    )

    for _, station_a in stations.iterrows():

        for _, station_b in stations.iterrows():

            distance = haversine_distance(
                station_a["latitude"],
                station_a["longitude"],
                station_b["latitude"],
                station_b["longitude"]
            )

            distance_matrix.loc[
                station_a["station_id"],
                station_b["station_id"]
            ] = distance

    return distance_matrix

In [ ]:
distance_matrix = create_distance_matrix(stations)

display(distance_matrix.round(2))

        42131   42139   42176   42181   42182
42131    0.00  185.37   90.60  150.33  156.85
42139  185.37    0.00  104.20   70.98   64.07
42176   90.60  104.20    0.00   59.88   66.26
42181  150.33   70.98   59.88    0.00    8.34
42182  156.85   64.07   66.26    8.34    0.00

In [ ]:
def get_neighbors(
    station_id,
    distance_matrix,
    max_distance_km=100
):
    """
    Return stations within max_distance_km,
    excluding the station itself.
    """

    distances = distance_matrix.loc[station_id]

    neighbors = distances[
        (distances > 0) &
        (distances <= max_distance_km)
    ].sort_values()

    return neighbors

In [ ]:
station_id = 42131

neighbors = get_neighbors(
    station_id,
    distance_matrix
)

print("Station:", station_id)
print("Neighbors:")
print(neighbors)

Station: 42131
Neighbors:
42176    90.597155
Name: 42131, dtype: float64

In [ ]:
def get_neighbor_average(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Calculate the average value of a parameter
    from nearby stations at the same timestamp.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return np.nan

    neighbor_ids = neighbors.index.tolist()

    subset = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ]

    values = subset[parameter].dropna()

    if len(values) == 0:
        return np.nan

    return values.mean()

In [ ]:
test_row = df.iloc[0]

test_station = test_row["station_id"]
test_timestamp = test_row["timestamp"]

print("Station:", test_station)
print("Timestamp:", test_timestamp)
print("Temperature:", test_row["temperature"])

Station: 42131
Timestamp: 2025-01-01 00:00:00
Temperature: 5.4

In [ ]:
neighbor_temp = get_neighbor_average(
    df,
    test_station,
    test_timestamp,
    "temperature",
    distance_matrix
)

print("Neighbor temperature average:", neighbor_temp)

Neighbor temperature average: 7.7

In [77]:
def calculate_spatial_deviation(
    station_value,
    neighbor_average
):
    if pd.isna(neighbor_average):
        return np.nan

    return abs(station_value - neighbor_average)

In [78]:
station_value = test_row["temperature"]

spatial_difference = calculate_spatial_deviation(
    station_value,
    neighbor_temp
)

print("Station value:", station_value)
print("Neighbor average:", neighbor_temp)
print("Spatial difference:", spatial_difference)

Station value: 5.4
Neighbor average: 7.7
Spatial difference: 2.3

In [80]:
temperature_55 = df[
    df["temperature"] == 55
]

print("Number of 55°C observations:", len(temperature_55))

display(
    temperature_55[
        [
            "station_id",
            "station_name",
            "timestamp",
            "temperature",
            "is_anomaly",
            "fault_type"
        ]
    ]
)

Number of 55°C observations: 0

Empty DataFrame
Columns: [station_id, station_name, timestamp, temperature, is_anomaly, fault_type]
Index: []

In [82]:
print("Temperature dtype:", df["temperature"].dtype)
print("Number of temperature values:", df["temperature"].notna().sum())

print("\nTemperature range:")
print("Min:", df["temperature"].min())
print("Max:", df["temperature"].max())

print("\nHighest temperatures:")
display(
    df[["station_id", "station_name", "timestamp", "temperature"]]
    .sort_values("temperature", ascending=False)
    .head(20)
)

Temperature dtype: float64
Number of temperature values: 43074

Temperature range:
Min: 4.0
Max: 51.1

Highest temperatures:

       station_id station_name           timestamp  temperature
21333       42176       Rohtak 2025-07-07 10:00:00         51.1
39732       42182   Safdarjung 2025-08-13 17:00:00         50.7
21332       42176       Rohtak 2025-07-07 09:00:00         50.7
39733       42182   Safdarjung 2025-08-13 18:00:00         50.3
21331       42176       Rohtak 2025-07-07 08:00:00         50.1
21330       42176       Rohtak 2025-07-07 07:00:00         50.1
39734       42182   Safdarjung 2025-08-13 19:00:00         50.0
39735       42182   Safdarjung 2025-08-13 20:00:00         49.8
21334       42176       Rohtak 2025-07-07 11:00:00         49.5
21329       42176       Rohtak 2025-07-07 06:00:00         49.4
22239       42176       Rohtak 2025-08-14 04:00:00         48.9
22238       42176       Rohtak 2025-08-14 03:00:00         48.6
29764       42181        Palam 2025-06-24 10:00:00         48.0
29765       42181        Palam 2025-06-24 11:00:00         47.0
30525       42181        Palam 2025-07-26 03:00:00         45.0
30524       42181        Palam 2025-07-26 02:00:00         44.0
29428       42181        Palam 2025-06-10 10:00:00         44.0
29404       42181        Palam 2025-06-09 10:00:00         44.0
29430       42181        Palam 2025-06-10 12:00:00         44.0
29427       42181        Palam 2025-06-10 09:00:00         44.0

In [ ]:
def analyze_spatial_anomaly(
    df,
    row,
    parameter,
    distance_matrix,
    max_distance_km=100
):

    station_id = row["station_id"]
    timestamp = row["timestamp"]
    station_value = row[parameter]

    neighbor_average = get_neighbor_average(
        df,
        station_id,
        timestamp,
        parameter,
        distance_matrix,
        max_distance_km
    )

    spatial_difference = calculate_spatial_deviation(
        station_value,
        neighbor_average
    )

    return {
        "station_id": station_id,
        "timestamp": timestamp,
        "parameter": parameter,
        "station_value": station_value,
        "neighbor_average": neighbor_average,
        "spatial_difference": spatial_difference
    }

In [ ]:
result = analyze_spatial_anomaly(
    df,
    df.iloc[0],
    "temperature",
    distance_matrix
)

print(result)

{'station_id': np.int64(42131), 'timestamp': Timestamp('2025-01-01 00:00:00'), 'parameter': 'temperature', 'station_value': np.float64(5.4), 'neighbor_average': np.float64(7.7), 'spatial_difference': np.float64(2.3)}

In [ ]:
def classify_weather_vs_sensor(
    ml_anomaly,
    temporal_anomaly,
    station_value,
    neighbor_average,
    spatial_threshold
):

    evidence = 0
    reasons = []

    if ml_anomaly:
        evidence += 1
        reasons.append("ML anomaly detected")

    if temporal_anomaly:
        evidence += 1
        reasons.append("Temporal deviation detected")

    if not pd.isna(neighbor_average):

        spatial_difference = abs(
            station_value - neighbor_average
        )

        if spatial_difference > spatial_threshold:

            evidence += 1
            reasons.append(
                "Value differs significantly from nearby stations"
            )

    if evidence >= 3:
        classification = "Sensor Fault"

    elif evidence == 2:
        classification = "Suspicious"

    else:
        classification = "Likely Weather Event"

    return classification, evidence, reasons

In [ ]:
def correct_value(
    original_value,
    neighbor_average,
    last_valid_value=None
):

    if not pd.isna(neighbor_average):
        return neighbor_average

    if last_valid_value is not None:
        return last_valid_value

    return original_value

In [ ]:
def update_health_score(
    current_score,
    fault_type
):

    penalty = FAULT_PENALTIES.get(
        fault_type,
        5
    )

    new_score = max(
        0,
        current_score - penalty
    )

    return new_score

In [ ]:
def get_health_status(score):

    if score >= 80:
        return "GREEN"

    elif score >= 50:
        return "YELLOW"

    return "RED"

In [ ]:
print(open("src/spatial_analysis.py").read())

In [72]:
from src.spatial_analysis import haversine_distance
print(
    haversine_distance(
        28.6139, 77.2090,
        28.5355, 77.3910
    )
)

19.795386048614194

In [73]:
from src.spatial_analysis import haversine_distance


def create_distance_matrix(stations):
    """
    Create a matrix containing the distance (km)
    between every pair of AWS stations.
    """

    station_ids = stations["station_id"].tolist()

    distance_matrix = pd.DataFrame(
        index=station_ids,
        columns=station_ids,
        dtype=float
    )

    for _, station_a in stations.iterrows():

        for _, station_b in stations.iterrows():

            distance = haversine_distance(
                station_a["latitude"],
                station_a["longitude"],
                station_b["latitude"],
                station_b["longitude"]
            )

            distance_matrix.loc[
                station_a["station_id"],
                station_b["station_id"]
            ] = distance

    return distance_matrix

In [74]:
stations = (
    df[
        ["station_id", "station_name", "latitude", "longitude"]
    ]
    .drop_duplicates("station_id")
    .reset_index(drop=True)
)

print("Number of stations:", len(stations))

display(stations)

distance_matrix = create_distance_matrix(stations)

display(distance_matrix.round(2))

Number of stations: 5

   station_id station_name  latitude  longitude
0       42131       Hissar   29.1667    75.7333
1       42139       Meerut   29.0167    77.6333
2       42176       Rohtak   28.8333    76.5833
3       42181        Palam   28.5667    77.1167
4       42182   Safdarjung   28.5833    77.2000

        42131   42139   42176   42181   42182
42131    0.00  185.37   90.60  150.33  156.85
42139  185.37    0.00  104.20   70.98   64.07
42176   90.60  104.20    0.00   59.88   66.26
42181  150.33   70.98   59.88    0.00    8.34
42182  156.85   64.07   66.26    8.34    0.00

In [ ]:
for station_id in distance_matrix.index:

    neighbors = get_nearest_neighbors(
        station_id,
        distance_matrix,
        n_neighbors=3
    )

    print(f"\nStation {station_id}")
    print(neighbors)

Station 42131
42176     90.597155
42181    150.327337
42182    156.854619
Name: 42131, dtype: float64

Station 42139
42182     64.070762
42181     70.979270
42176    104.204510
Name: 42139, dtype: float64

Station 42176
42181    59.877881
42182    66.257981
42131    90.597155
Name: 42176, dtype: float64

Station 42181
42182     8.341084
42176    59.877881
42139    70.979270
Name: 42181, dtype: float64

Station 42182
42181     8.341084
42139    64.070762
42176    66.257981
Name: 42182, dtype: float64

In [75]:
def get_neighbor_average(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Calculate the average value of a parameter
    from nearby stations at the same timestamp.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return np.nan

    neighbor_ids = neighbors.index.tolist()

    subset = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ]

    values = subset[parameter].dropna()

    if len(values) == 0:
        return np.nan

    return values.mean()

In [76]:
neighbor_temp = get_neighbor_average(
    df,
    test_row["station_id"],
    test_row["timestamp"],
    "temperature",
    distance_matrix,
    max_distance_km=100
)

print("Station temperature:", test_row["temperature"])
print("Neighbor average:", neighbor_temp)

Station temperature: 5.4
Neighbor average: 7.7

In [ ]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

test_row = df.iloc[0]

print("Station:", test_row["station_id"])
print("Timestamp:", test_row["timestamp"])
print("Temperature:", test_row["temperature"])

Station: 42131
Timestamp: 2025-01-01 00:00:00
Temperature: 5.4

In [ ]:
neighbor_average = get_neighbor_average(
    df=df,
    station_id=test_row["station_id"],
    timestamp=test_row["timestamp"],
    parameter="temperature",
    distance_matrix=distance_matrix,
    n_neighbors=3
)

print("Neighbor temperature average:", neighbor_average)

Neighbor temperature average: 9.033333333333333

In [ ]:
def calculate_spatial_deviation(
    station_value,
    neighbor_average
):
    """
    Calculate absolute difference between
    station value and neighboring average.
    """

    if pd.isna(neighbor_average):
        return np.nan

    return abs(
        station_value - neighbor_average
    )

In [ ]:
spatial_deviation = calculate_spatial_deviation(
    test_row["temperature"],
    neighbor_average
)

print("Station temperature:", test_row["temperature"])
print("Neighbor average:", neighbor_average)
print("Spatial deviation:", spatial_deviation)

Station temperature: 5.4
Neighbor average: 9.033333333333333
Spatial deviation: 3.633333333333333

In [ ]:
neighbors = get_nearest_neighbors(
    test_row["station_id"],
    distance_matrix,
    n_neighbors=3
)

print("Test station:", test_row["station_id"])
print("\nNearest stations:")
print(neighbors)

Test station: 42131

Nearest stations:
42176     90.597155
42181    150.327337
42182    156.854619
Name: 42131, dtype: float64

In [ ]:
neighbor_ids = neighbors.index.tolist()

neighbor_data = df[
    (df["timestamp"] == test_row["timestamp"]) &
    (df["station_id"].isin(neighbor_ids))
]

display(
    neighbor_data[
        [
            "station_id",
            "station_name",
            "temperature",
            "humidity",
            "pressure",
            "is_anomaly",
            "fault_type"
        ]
    ]
)

,station_id,station_name,temperature,humidity,pressure,is_anomaly,fault_type
17061,42176,Rohtak,7.7,98.0,1019.1,0,normal
25578,42181,Palam,9.0,97.0,1020.2,0,normal
34339,42182,Safdarjung,10.4,92.0,1019.2,0,normal

In [ ]:
display(distance_matrix.round(2))

        42131   42139   42176   42181   42182
42131    0.00  185.37   90.60  150.33  156.85
42139  185.37    0.00  104.20   70.98   64.07
42176   90.60  104.20    0.00   59.88   66.26
42181  150.33   70.98   59.88    0.00    8.34
42182  156.85   64.07   66.26    8.34    0.00

In [ ]:
display(
    stations[
        ["station_id", "station_name", "latitude", "longitude"]
    ]
)

   station_id station_name  latitude  longitude
0       42131       Hissar   29.1667    75.7333
1       42139       Meerut   29.0167    77.6333
2       42176       Rohtak   28.8333    76.5833
3       42181        Palam   28.5667    77.1167
4       42182   Safdarjung   28.5833    77.2000

In [ ]:
neighbors = get_neighbors(
    test_row["station_id"],
    distance_matrix,
    max_distance_km=100
)

print("Station:", test_row["station_id"])
print("Neighbors within 100 km:")
print(neighbors)

Station: 42131
Neighbors within 100 km:
42176    90.597155
Name: 42131, dtype: float64

In [ ]:
neighbor_ids = neighbors.index.tolist()

neighbor_data = df[
    (df["timestamp"] == test_row["timestamp"]) &
    (df["station_id"].isin(neighbor_ids))
]

display(
    neighbor_data[
        [
            "station_id",
            "station_name",
            "temperature",
            "is_anomaly",
            "fault_type"
        ]
    ]
)

       station_id station_name  temperature  is_anomaly fault_type
17061       42176       Rohtak          7.7           0     normal

In [ ]:
def get_neighbor_consensus(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Check whether nearby stations agree with each other
    and whether they are flagged as anomalous.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return {
            "neighbor_count": 0,
            "normal_neighbors": 0,
            "anomalous_neighbors": 0,
            "neighbor_average": np.nan,
            "neighbor_values": []
        }

    neighbor_ids = neighbors.index.tolist()

    neighbor_data = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ].copy()

    # Remove missing parameter values
    neighbor_data = neighbor_data.dropna(
        subset=[parameter]
    )

    if len(neighbor_data) == 0:
        return {
            "neighbor_count": 0,
            "normal_neighbors": 0,
            "anomalous_neighbors": 0,
            "neighbor_average": np.nan,
            "neighbor_values": []
        }

    neighbor_values = neighbor_data[parameter].tolist()

    # Count anomaly status
    if "is_anomaly" in neighbor_data.columns:

        anomalous_neighbors = int(
            (neighbor_data["is_anomaly"] == 1).sum()
        )

        normal_neighbors = int(
            (neighbor_data["is_anomaly"] == 0).sum()
        )

    else:
        anomalous_neighbors = 0
        normal_neighbors = len(neighbor_data)

    return {
        "neighbor_count": len(neighbor_data),
        "normal_neighbors": normal_neighbors,
        "anomalous_neighbors": anomalous_neighbors,
        "neighbor_average": np.mean(neighbor_values),
        "neighbor_values": neighbor_values
    }

In [ ]:
consensus = get_neighbor_consensus(
    df=df,
    station_id=test_row["station_id"],
    timestamp=test_row["timestamp"],
    parameter="temperature",
    distance_matrix=distance_matrix,
    max_distance_km=100
)

print(consensus)

{'neighbor_count': 1, 'normal_neighbors': 1, 'anomalous_neighbors': 0, 'neighbor_average': np.float64(7.7), 'neighbor_values': [7.7]}

In [83]:
print("Fault types:")
print(df["fault_type"].value_counts(dropna=False))

Fault types:
fault_type
normal                        42778
multivariate_inconsistency       60
temperature_missing              26
pressure_missing                 26
pressure_spike                   25
pressure_drift                   24
temperature_frozen               22
humidity_drift                   22
humidity_frozen                  21
temperature_drift                19
humidity_spike                   18
temperature_spike                15
humidity_drop                    12
pressure_frozen                  10
humidity_missing                  9
temperature_drop                  9
pressure_drop                     4
Name: count, dtype: int64

In [84]:
print("Anomaly counts:")
print(df["is_anomaly"].value_counts(dropna=False))

Anomaly counts:
is_anomaly
0    42778
1      322
Name: count, dtype: int64

In [85]:
display(
    df[df["is_anomaly"] == 1][
        [
            "station_id",
            "station_name",
            "timestamp",
            "temperature",
            "humidity",
            "pressure",
            "is_anomaly",
            "fault_type"
        ]
    ].head(30)
)

,station_id,station_name,timestamp,temperature,humidity,pressure,is_anomaly,fault_type
512,42131,Hissar,2025-01-22 08:00:00,20.5,63.0,1003.7,1,pressure_drop
513,42131,Hissar,2025-01-22 09:00:00,22.8,43.0,1003.2,1,pressure_drop
1069,42131,Hissar,2025-02-14 13:00:00,18.0,71.0,1012.1,1,pressure_drift
1070,42131,Hissar,2025-02-14 14:00:00,17.7,67.0,1012.8,1,pressure_drift
1071,42131,Hissar,2025-02-14 15:00:00,16.2,68.0,1015.5,1,pressure_drift
1072,42131,Hissar,2025-02-14 16:00:00,16.4,63.0,1014.2,1,pressure_drift
1073,42131,Hissar,2025-02-14 17:00:00,15.1,65.0,1014.6,1,pressure_drift
1074,42131,Hissar,2025-02-14 18:00:00,14.8,70.0,1016.3,1,pressure_drift
1816,42131,Hissar,2025-03-22 05:00:00,26.0,41.0,1014.5,1,humidity_frozen
1817,42131,Hissar,2025-03-22 06:00:00,30.2,41.0,1015.5,1,humidity_frozen
1853,42131,Hissar,2025-03-23 18:00:00,18.4,79.0,1016.3,1,pressure_drift
2049,42131,Hissar,2025-03-31 22:00:00,17.5,38.0,1008.4,1,pressure_drift
2368,42131,Hissar,2025-04-14 05:00:00,33.8,27.2,1009.2,1,humidity_drift
2369,42131,Hissar,2025-04-14 06:00:00,35.2,24.4,1008.7,1,humidity_drift
2370,42131,Hissar,2025-04-14 07:00:00,35.7,24.6,1008.2,1,humidity_drift
2371,42131,Hissar,2025-04-14 08:00:00,36.2,23.8,1007.4,1,humidity_drift
2681,42131,Hissar,2025-05-01 07:00:00,18.3,23.0,1006.6,1,temperature_drop
2682,42131,Hissar,2025-05-01 08:00:00,19.1,19.0,1006.1,1,temperature_drop
3343,42131,Hissar,2025-05-28 21:00:00,28.6,NaN,995.8,1,humidity_missing
3344,42131,Hissar,2025-05-28 22:00:00,31.3,NaN,994.9,1,humidity_missing
3345,42131,Hissar,2025-05-28 23:00:00,30.5,NaN,995.3,1,humidity_missing
3346,42131,Hissar,2025-05-29 00:00:00,29.3,NaN,995.7,1,humidity_missing
3347,42131,Hissar,2025-05-29 01:00:00,29.7,NaN,996.6,1,humidity_missing
3348,42131,Hissar,2025-05-29 02:00:00,31.2,NaN,997.0,1,humidity_missing
3440,42131,Hissar,2025-06-01 22:00:00,30.9,43.0,996.4,1,multivariate_inconsistency
3441,42131,Hissar,2025-06-01 23:00:00,30.3,45.0,996.6,1,multivariate_inconsistency
3442,42131,Hissar,2025-06-02 00:00:00,29.1,51.0,997.1,1,multivariate_inconsistency
3443,42131,Hissar,2025-06-02 01:00:00,29.5,54.0,997.7,1,multivariate_inconsistency
3444,42131,Hissar,2025-06-02 02:00:00,34.1,49.0,998.2,1,multivariate_inconsistency
3445,42131,Hissar,2025-06-02 03:00:00,36.0,45.0,998.6,1,multivariate_inconsistency

In [86]:
test_df = df.copy()

print("Original df shape:", df.shape)
print("Test df shape:", test_df.shape)

Original df shape: (43100, 34)
Test df shape: (43100, 34)

In [87]:
test_index = test_df["temperature"].idxmax()

fault_row = test_df.loc[test_index]

print("Station ID:", fault_row["station_id"])
print("Station name:", fault_row["station_name"])
print("Timestamp:", fault_row["timestamp"])
print("Original temperature:", fault_row["temperature"])
print("Original fault type:", fault_row["fault_type"])

Station ID: 42176
Station name: Rohtak
Timestamp: 2025-07-07 10:00:00
Original temperature: 51.1
Original fault type: multivariate_inconsistency

In [88]:
test_df.loc[test_index, "temperature"] = 55.0

print(
    test_df.loc[
        test_index,
        ["station_id", "station_name", "timestamp", "temperature"]
    ]
)

station_id                    42176
station_name                 Rohtak
timestamp       2025-07-07 10:00:00
temperature                    55.0
Name: 21333, dtype: object

In [89]:
print("Original df temperature:", df.loc[test_index, "temperature"])
print("Test df temperature:", test_df.loc[test_index, "temperature"])

Original df temperature: 51.1
Test df temperature: 55.0

In [90]:
neighbors_55 = get_neighbors(
    station_id=fault_row["station_id"],
    distance_matrix=distance_matrix,
    max_distance_km=100
)

print("Test station:", fault_row["station_id"])
print("Test station name:", fault_row["station_name"])

print("\nNeighbors within 100 km:")
print(neighbors_55)

Test station: 42176
Test station name: Rohtak

Neighbors within 100 km:
42181    59.877881
42182    66.257981
42131    90.597155
Name: 42176, dtype: float64

In [91]:
neighbor_ids_55 = neighbors_55.index.tolist()

neighbor_data_55 = test_df[
    (test_df["timestamp"] == fault_row["timestamp"]) &
    (test_df["station_id"].isin(neighbor_ids_55))
].copy()

display(
    neighbor_data_55[
        [
            "station_id",
            "station_name",
            "timestamp",
            "temperature",
            "humidity",
            "pressure",
            "is_anomaly",
            "fault_type"
        ]
    ]
)

,station_id,station_name,timestamp,temperature,humidity,pressure,is_anomaly,fault_type
4292,42131,Hissar,2025-07-07 10:00:00,35.8,56.0,995.8,0,normal
30076,42181,Palam,2025-07-07 10:00:00,33.0,59.0,999.0,0,normal
38837,42182,Safdarjung,2025-07-07 10:00:00,33.9,60.0,996.7,0,normal

In [92]:
neighbor_average_55 = get_neighbor_average(
    df=test_df,
    station_id=fault_row["station_id"],
    timestamp=fault_row["timestamp"],
    parameter="temperature",
    distance_matrix=distance_matrix,
    max_distance_km=100
)

print("Station temperature:", test_df.loc[test_index, "temperature"])
print("Neighbor temperature average:", neighbor_average_55)

Station temperature: 55.0
Neighbor temperature average: 34.23333333333333

In [93]:
spatial_deviation_55 = calculate_spatial_deviation(
    station_value=test_df.loc[test_index, "temperature"],
    neighbor_average=neighbor_average_55
)

print("Station temperature:", test_df.loc[test_index, "temperature"])
print("Neighbor average:", neighbor_average_55)
print("Spatial deviation:", spatial_deviation_55)

Station temperature: 55.0
Neighbor average: 34.23333333333333
Spatial deviation: 20.766666666666673

In [94]:
consensus_55 = get_neighbor_consensus(
    df=test_df,
    station_id=fault_row["station_id"],
    timestamp=fault_row["timestamp"],
    parameter="temperature",
    distance_matrix=distance_matrix,
    max_distance_km=100
)

print("55°C Test — Neighbor Consensus")
print(consensus_55)

55°C Test — Neighbor Consensus
{'neighbor_count': 3, 'normal_neighbors': 3, 'anomalous_neighbors': 0, 'neighbor_average': np.float64(34.23333333333333), 'neighbor_values': [35.8, 33.0, 33.9]}

In [95]:
print("Neighbor count:", consensus_55["neighbor_count"])
print("Normal neighbors:", consensus_55["normal_neighbors"])
print("Anomalous neighbors:", consensus_55["anomalous_neighbors"])
print("Neighbor average:", consensus_55["neighbor_average"])
print("Neighbor values:", consensus_55["neighbor_values"])

Neighbor count: 3
Normal neighbors: 3
Anomalous neighbors: 0
Neighbor average: 34.23333333333333
Neighbor values: [35.8, 33.0, 33.9]

In [96]:
classification, evidence, reasons = classify_weather_vs_sensor(
    ml_anomaly=True,
    temporal_anomaly=True,
    station_value=55.0,
    neighbor_average=neighbor_average_55,
    spatial_threshold=5.0
)

print("Classification:", classification)
print("Evidence score:", evidence)

print("\nReasons:")
for reason in reasons:
    print("-", reason)

Classification: Sensor Fault
Evidence score: 3

Reasons:
- ML anomaly detected
- Temporal deviation detected
- Value differs significantly from nearby stations

In [97]:
corrected_55 = correct_value(
    original_value=55.0,
    neighbor_average=neighbor_average_55
)

print("Original value:", 55.0)
print("Neighbor average:", neighbor_average_55)
print("Corrected value:", corrected_55)

Original value: 55.0
Neighbor average: 34.23333333333333
Corrected value: 34.23333333333333

In [98]:
print("FAULT_PENALTIES exists:", "FAULT_PENALTIES" in globals())

FAULT_PENALTIES exists: False

In [99]:
FAULT_PENALTIES = {
    "temperature_spike": 15,
    "temperature_drift": 10,
    "temperature_frozen": 12,
    "temperature_drop": 10,
    "humidity_spike": 8,
    "humidity_drift": 8,
    "humidity_frozen": 10,
    "humidity_drop": 8,
    "pressure_spike": 8,
    "pressure_drift": 8,
    "pressure_frozen": 10,
    "pressure_drop": 8,
    "temperature_missing": 5,
    "humidity_missing": 5,
    "pressure_missing": 5,
    "multivariate_inconsistency": 10
}

print(FAULT_PENALTIES)

{'temperature_spike': 15, 'temperature_drift': 10, 'temperature_frozen': 12, 'temperature_drop': 10, 'humidity_spike': 8, 'humidity_drift': 8, 'humidity_frozen': 10, 'humidity_drop': 8, 'pressure_spike': 8, 'pressure_drift': 8, 'pressure_frozen': 10, 'pressure_drop': 8, 'temperature_missing': 5, 'humidity_missing': 5, 'pressure_missing': 5, 'multivariate_inconsistency': 10}

In [100]:
initial_health = 100

new_health = update_health_score(
    current_score=initial_health,
    fault_type="temperature_spike"
)

health_status = get_health_status(new_health)

print("Initial health:", initial_health)
print("Fault type:", "temperature_spike")
print("New health:", new_health)
print("Health status:", health_status)

Initial health: 100
Fault type: temperature_spike
New health: 85
Health status: GREEN

In [101]:
final_55_result = {
    "station_id": fault_row["station_id"],
    "station_name": fault_row["station_name"],
    "timestamp": fault_row["timestamp"],
    "parameter": "temperature",
    "original_value": 55.0,
    "neighbor_average": neighbor_average_55,
    "spatial_deviation": spatial_deviation_55,
    "neighbor_count": consensus_55["neighbor_count"],
    "normal_neighbors": consensus_55["normal_neighbors"],
    "anomalous_neighbors": consensus_55["anomalous_neighbors"],
    "classification": classification,
    "evidence_score": evidence,
    "explanation": reasons,
    "corrected_value": corrected_55,
    "health_score": new_health,
    "health_status": health_status
}

print("FINAL 55°C TEST RESULT")
print("=" * 50)

for key, value in final_55_result.items():
    print(f"{key}: {value}")

FINAL 55°C TEST RESULT
==================================================
station_id: 42176
station_name: Rohtak
timestamp: 2025-07-07 10:00:00
parameter: temperature
original_value: 55.0
neighbor_average: 34.23333333333333
spatial_deviation: 20.766666666666673
neighbor_count: 3
normal_neighbors: 3
anomalous_neighbors: 0
classification: Sensor Fault
evidence_score: 3
explanation: ['ML anomaly detected', 'Temporal deviation detected', 'Value differs significantly from nearby stations']
corrected_value: 34.23333333333333
health_score: 85
health_status: GREEN

In [103]:
print("===== spatial_analysis.py =====")
print(open("src/spatial_analysis.py").read())

===== spatial_analysis.py =====

import pandas as pd
import numpy as np
from math import radians, sin, cos, sqrt, atan2


def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the distance between two latitude/longitude
    coordinates in kilometers.
    """

    R = 6371.0  # Earth radius in km

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2) ** 2
        + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(
        sqrt(a),
        sqrt(1 - a)
    )

    return R * c

In [104]:
print("===== diagnosis.py =====")
print(open("src/diagnosis.py").read())

===== diagnosis.py =====

In [105]:
print("===== sensor_health.py =====")
print(open("src/sensor_health.py").read())

===== sensor_health.py =====

In [106]:
%%writefile src/spatial_analysis.py

import pandas as pd
import numpy as np
from math import radians, sin, cos, sqrt, atan2


def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the distance between two latitude/longitude
    coordinates in kilometers.
    """

    R = 6371.0

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2) ** 2
        + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(
        sqrt(a),
        sqrt(1 - a)
    )

    return R * c


def create_distance_matrix(stations):
    """
    Create a distance matrix containing the distance
    in kilometers between every pair of stations.

    stations must contain:
        station_id
        latitude
        longitude
    """

    station_ids = stations["station_id"].tolist()

    distance_matrix = pd.DataFrame(
        index=station_ids,
        columns=station_ids,
        dtype=float
    )

    for _, station_a in stations.iterrows():

        for _, station_b in stations.iterrows():

            distance = haversine_distance(
                station_a["latitude"],
                station_a["longitude"],
                station_b["latitude"],
                station_b["longitude"]
            )

            distance_matrix.loc[
                station_a["station_id"],
                station_b["station_id"]
            ] = distance

    return distance_matrix


def get_neighbors(
    station_id,
    distance_matrix,
    max_distance_km=100
):
    """
    Return stations within max_distance_km.

    The target station itself is excluded.
    """

    distances = distance_matrix.loc[station_id]

    neighbors = (
        distances[
            (distances > 0) &
            (distances <= max_distance_km)
        ]
        .sort_values()
    )

    return neighbors


def get_neighbor_average(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Calculate the average value of a parameter
    from nearby stations at the same timestamp.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return np.nan

    neighbor_ids = neighbors.index.tolist()

    subset = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ]

    values = subset[parameter].dropna()

    if len(values) == 0:
        return np.nan

    return values.mean()


def calculate_spatial_deviation(
    station_value,
    neighbor_average
):
    """
    Calculate the absolute difference between
    the station value and neighboring average.
    """

    if pd.isna(neighbor_average):
        return np.nan

    return abs(
        station_value - neighbor_average
    )


def get_neighbor_consensus(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Check whether nearby stations agree with each other
    and whether they are flagged as anomalous.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return {
            "neighbor_count": 0,
            "normal_neighbors": 0,
            "anomalous_neighbors": 0,
            "neighbor_average": np.nan,
            "neighbor_values": []
        }

    neighbor_ids = neighbors.index.tolist()

    neighbor_data = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ].copy()

    neighbor_data = neighbor_data.dropna(
        subset=[parameter]
    )

    if len(neighbor_data) == 0:
        return {
            "neighbor_count": 0,
            "normal_neighbors": 0,
            "anomalous_neighbors": 0,
            "neighbor_average": np.nan,
            "neighbor_values": []
        }

    neighbor_values = neighbor_data[parameter].tolist()

    if "is_anomaly" in neighbor_data.columns:

        anomalous_neighbors = int(
            (neighbor_data["is_anomaly"] == 1).sum()
        )

        normal_neighbors = int(
            (neighbor_data["is_anomaly"] == 0).sum()
        )

    else:

        anomalous_neighbors = 0
        normal_neighbors = len(neighbor_data)

    return {
        "neighbor_count": len(neighbor_data),
        "normal_neighbors": normal_neighbors,
        "anomalous_neighbors": anomalous_neighbors,
        "neighbor_average": np.mean(neighbor_values),
        "neighbor_values": neighbor_values
    }

Overwriting src/spatial_analysis.py

In [107]:
print(open("src/spatial_analysis.py").read())

import pandas as pd
import numpy as np
from math import radians, sin, cos, sqrt, atan2


def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate the distance between two latitude/longitude
    coordinates in kilometers.
    """

    R = 6371.0

    lat1, lon1, lat2, lon2 = map(
        radians,
        [lat1, lon1, lat2, lon2]
    )

    dlat = lat2 - lat1
    dlon = lon2 - lon1

    a = (
        sin(dlat / 2) ** 2
        + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    )

    c = 2 * atan2(
        sqrt(a),
        sqrt(1 - a)
    )

    return R * c


def create_distance_matrix(stations):
    """
    Create a distance matrix containing the distance
    in kilometers between every pair of stations.

    stations must contain:
        station_id
        latitude
        longitude
    """

    station_ids = stations["station_id"].tolist()

    distance_matrix = pd.DataFrame(
        index=station_ids,
        columns=station_ids,
        dtype=float
    )

    for _, station_a in stations.iterrows():

        for _, station_b in stations.iterrows():

            distance = haversine_distance(
                station_a["latitude"],
                station_a["longitude"],
                station_b["latitude"],
                station_b["longitude"]
            )

            distance_matrix.loc[
                station_a["station_id"],
                station_b["station_id"]
            ] = distance

    return distance_matrix


def get_neighbors(
    station_id,
    distance_matrix,
    max_distance_km=100
):
    """
    Return stations within max_distance_km.

    The target station itself is excluded.
    """

    distances = distance_matrix.loc[station_id]

    neighbors = (
        distances[
            (distances > 0) &
            (distances <= max_distance_km)
        ]
        .sort_values()
    )

    return neighbors


def get_neighbor_average(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Calculate the average value of a parameter
    from nearby stations at the same timestamp.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return np.nan

    neighbor_ids = neighbors.index.tolist()

    subset = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ]

    values = subset[parameter].dropna()

    if len(values) == 0:
        return np.nan

    return values.mean()


def calculate_spatial_deviation(
    station_value,
    neighbor_average
):
    """
    Calculate the absolute difference between
    the station value and neighboring average.
    """

    if pd.isna(neighbor_average):
        return np.nan

    return abs(
        station_value - neighbor_average
    )


def get_neighbor_consensus(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    max_distance_km=100
):
    """
    Check whether nearby stations agree with each other
    and whether they are flagged as anomalous.
    """

    neighbors = get_neighbors(
        station_id,
        distance_matrix,
        max_distance_km
    )

    if len(neighbors) == 0:
        return {
            "neighbor_count": 0,
            "normal_neighbors": 0,
            "anomalous_neighbors": 0,
            "neighbor_average": np.nan,
            "neighbor_values": []
        }

    neighbor_ids = neighbors.index.tolist()

    neighbor_data = df[
        (df["timestamp"] == timestamp) &
        (df["station_id"].isin(neighbor_ids))
    ].copy()

    neighbor_data = neighbor_data.dropna(
        subset=[parameter]
    )

    if len(neighbor_data) == 0:
        return {
            "neighbor_count": 0,
            "normal_neighbors": 0,
            "anomalous_neighbors": 0,
            "neighbor_average": np.nan,
            "neighbor_values": []
        }

    neighbor_values = neighbor_data[parameter].tolist()

    if "is_anomaly" in neighbor_data.columns:

        anomalous_neighbors = int(
            (neighbor_data["is_anomaly"] == 1).sum()
        )

        normal_neighbors = int(
            (neighbor_data["is_anomaly"] == 0).sum()
        )

    else:

        anomalous_neighbors = 0
        normal_neighbors = len(neighbor_data)

    return {
        "neighbor_count": len(neighbor_data),
        "normal_neighbors": normal_neighbors,
        "anomalous_neighbors": anomalous_neighbors,
        "neighbor_average": np.mean(neighbor_values),
        "neighbor_values": neighbor_values
    }

In [108]:
import importlib
import src.spatial_analysis as spatial_analysis

importlib.reload(spatial_analysis)

print("spatial_analysis.py loaded successfully")

spatial_analysis.py loaded successfully

In [109]:
stations_test = (
    df[
        ["station_id", "station_name", "latitude", "longitude"]
    ]
    .drop_duplicates("station_id")
    .reset_index(drop=True)
)

print("Number of stations:", len(stations_test))
display(stations_test)

Number of stations: 5

   station_id station_name  latitude  longitude
0       42131       Hissar   29.1667    75.7333
1       42139       Meerut   29.0167    77.6333
2       42176       Rohtak   28.8333    76.5833
3       42181        Palam   28.5667    77.1167
4       42182   Safdarjung   28.5833    77.2000

In [110]:
distance_matrix_test = spatial_analysis.create_distance_matrix(
    stations_test
)

print("Distance matrix shape:", distance_matrix_test.shape)

display(distance_matrix_test.round(2))

Distance matrix shape: (5, 5)

        42131   42139   42176   42181   42182
42131    0.00  185.37   90.60  150.33  156.85
42139  185.37    0.00  104.20   70.98   64.07
42176   90.60  104.20    0.00   59.88   66.26
42181  150.33   70.98   59.88    0.00    8.34
42182  156.85   64.07   66.26    8.34    0.00

In [111]:
test_station_id = 42176

neighbors_test = spatial_analysis.get_neighbors(
    station_id=test_station_id,
    distance_matrix=distance_matrix_test,
    max_distance_km=100
)

print("Test station:", test_station_id)
print("\nNeighbors within 100 km:")
print(neighbors_test)

Test station: 42176

Neighbors within 100 km:
42181    59.877881
42182    66.257981
42131    90.597155
Name: 42176, dtype: float64

In [112]:
test_timestamp = pd.Timestamp("2025-07-07 10:00:00")

neighbor_average_test = spatial_analysis.get_neighbor_average(
    df=df,
    station_id=test_station_id,
    timestamp=test_timestamp,
    parameter="temperature",
    distance_matrix=distance_matrix_test,
    max_distance_km=100
)

print("Neighbor temperature average:", neighbor_average_test)

Neighbor temperature average: 34.23333333333333

In [113]:
deviation_test = spatial_analysis.calculate_spatial_deviation(
    station_value=55.0,
    neighbor_average=neighbor_average_test
)

print("Station value:", 55.0)
print("Neighbor average:", neighbor_average_test)
print("Spatial deviation:", deviation_test)

Station value: 55.0
Neighbor average: 34.23333333333333
Spatial deviation: 20.766666666666673

In [114]:
consensus_test = spatial_analysis.get_neighbor_consensus(
    df=df,
    station_id=test_station_id,
    timestamp=test_timestamp,
    parameter="temperature",
    distance_matrix=distance_matrix_test,
    max_distance_km=100
)

print("Neighbor consensus:")
print(consensus_test)

Neighbor consensus:
{'neighbor_count': 3, 'normal_neighbors': 3, 'anomalous_neighbors': 0, 'neighbor_average': np.float64(34.23333333333333), 'neighbor_values': [35.8, 33.0, 33.9]}

In [129]:
%%writefile src/diagnosis.py

import pandas as pd


def classify_weather_vs_sensor(
    ml_anomaly,
    temporal_anomaly,
    station_value,
    neighbor_average,
    spatial_threshold=5.0
):
    """
    Classify an anomalous observation as:
    - Sensor Fault
    - Suspicious
    - Likely Weather Event

    Evidence is collected from:
    1. ML anomaly detection
    2. Temporal anomaly detection
    3. Spatial deviation from nearby stations
    """

    evidence = 0
    reasons = []

    # ML evidence
    if ml_anomaly:
        evidence += 1
        reasons.append("ML anomaly detected")

    # Temporal evidence
    if temporal_anomaly:
        evidence += 1
        reasons.append("Temporal deviation detected")

    # Spatial evidence
    if not pd.isna(neighbor_average):

        spatial_difference = abs(
            station_value - neighbor_average
        )

        if spatial_difference > spatial_threshold:
            evidence += 1
            reasons.append(
                "Value differs significantly from nearby stations"
            )

    # Final classification
    if evidence >= 3:
        classification = "Sensor Fault"

    elif evidence == 2:
        classification = "Suspicious"

    else:
        classification = "Likely Weather Event"

    return classification, evidence, reasons


def correct_value(
    original_value,
    neighbor_average,
    last_valid_value=None
):
    """
    Correct a faulty value.

    Priority:
    1. Neighbor average
    2. Last valid value
    3. Original value
    """

    if not pd.isna(neighbor_average):
        return neighbor_average

    if last_valid_value is not None:
        return last_valid_value

    return original_value

Overwriting src/diagnosis.py

In [130]:
import importlib
import src.diagnosis as diagnosis

importlib.reload(diagnosis)

print("diagnosis.py loaded successfully")

diagnosis.py loaded successfully

In [117]:
classification_test, evidence_test, reasons_test = diagnosis.classify_weather_vs_sensor(
    ml_anomaly=True,
    temporal_anomaly=True,
    station_value=55.0,
    neighbor_average=neighbor_average_test,
    spatial_threshold=5.0
)

print("Classification:", classification_test)
print("Evidence score:", evidence_test)

print("\nReasons:")
for reason in reasons_test:
    print("-", reason)

Classification: Sensor Fault
Evidence score: 3

Reasons:
- ML anomaly detected
- Temporal deviation detected
- Value differs significantly from nearby stations

In [118]:
corrected_test = diagnosis.correct_value(
    original_value=55.0,
    neighbor_average=neighbor_average_test
)

print("Original value:", 55.0)
print("Neighbor average:", neighbor_average_test)
print("Corrected value:", corrected_test)

Original value: 55.0
Neighbor average: 34.23333333333333
Corrected value: 34.23333333333333

In [119]:
%%writefile src/sensor_health.py

# Penalty applied to sensor health score for different fault types

FAULT_PENALTIES = {
    "temperature_spike": 15,
    "temperature_drift": 10,
    "temperature_frozen": 12,
    "temperature_drop": 10,

    "humidity_spike": 8,
    "humidity_drift": 8,
    "humidity_frozen": 10,
    "humidity_drop": 8,

    "pressure_spike": 8,
    "pressure_drift": 8,
    "pressure_frozen": 10,
    "pressure_drop": 8,

    "temperature_missing": 5,
    "humidity_missing": 5,
    "pressure_missing": 5,

    "multivariate_inconsistency": 10
}


def update_health_score(
    current_score,
    fault_type
):
    """
    Reduce sensor health score according to fault type.

    Score is kept between 0 and 100.
    """

    penalty = FAULT_PENALTIES.get(
        fault_type,
        5
    )

    new_score = max(
        0,
        current_score - penalty
    )

    return new_score


def get_health_status(score):
    """
    Convert numerical health score into a status.

    80-100  -> GREEN
    50-79   -> YELLOW
    0-49    -> RED
    """

    if score >= 80:
        return "GREEN"

    elif score >= 50:
        return "YELLOW"

    return "RED"

Overwriting src/sensor_health.py

In [120]:
import importlib
import src.sensor_health as sensor_health

importlib.reload(sensor_health)

print("sensor_health.py loaded successfully")

sensor_health.py loaded successfully

In [121]:
print(sensor_health.FAULT_PENALTIES)

{'temperature_spike': 15, 'temperature_drift': 10, 'temperature_frozen': 12, 'temperature_drop': 10, 'humidity_spike': 8, 'humidity_drift': 8, 'humidity_frozen': 10, 'humidity_drop': 8, 'pressure_spike': 8, 'pressure_drift': 8, 'pressure_frozen': 10, 'pressure_drop': 8, 'temperature_missing': 5, 'humidity_missing': 5, 'pressure_missing': 5, 'multivariate_inconsistency': 10}

In [122]:
initial_health = 100

health_after_fault = sensor_health.update_health_score(
    current_score=initial_health,
    fault_type="temperature_spike"
)

print("Initial health:", initial_health)
print("Fault type:", "temperature_spike")
print("Health after fault:", health_after_fault)

Initial health: 100
Fault type: temperature_spike
Health after fault: 85

In [123]:
health_status_test = sensor_health.get_health_status(
    health_after_fault
)

print("Health score:", health_after_fault)
print("Health status:", health_status_test)

Health score: 85
Health status: GREEN

In [124]:
test_scores = [100, 85, 80, 79, 60, 50, 49, 20, 0]

for score in test_scores:
    status = sensor_health.get_health_status(score)
    print(f"{score} → {status}")

100 → GREEN
85 → GREEN
80 → GREEN
79 → YELLOW
60 → YELLOW
50 → YELLOW
49 → RED
20 → RED
0 → RED

In [125]:
high_temp_rows = df[df["temperature"] >= 40].copy()

print("Number of high-temperature observations:", len(high_temp_rows))

display(
    high_temp_rows[
        [
            "station_id",
            "station_name",
            "timestamp",
            "temperature",
            "is_anomaly",
            "fault_type"
        ]
    ].head(20)
)

Number of high-temperature observations: 407

,station_id,station_name,timestamp,temperature,is_anomaly,fault_type
2227,42131,Hissar,2025-04-08 08:00:00,40.0,0,normal
2228,42131,Hissar,2025-04-08 09:00:00,40.2,0,normal
2251,42131,Hissar,2025-04-09 08:00:00,40.4,0,normal
2252,42131,Hissar,2025-04-09 09:00:00,40.7,0,normal
2253,42131,Hissar,2025-04-09 10:00:00,40.6,0,normal
2442,42131,Hissar,2025-04-17 07:00:00,40.2,0,normal
2443,42131,Hissar,2025-04-17 08:00:00,41.1,0,normal
2444,42131,Hissar,2025-04-17 09:00:00,41.6,0,normal
2445,42131,Hissar,2025-04-17 10:00:00,41.6,0,normal
2446,42131,Hissar,2025-04-17 11:00:00,41.4,0,normal
2451,42131,Hissar,2025-04-18 12:00:00,41.4,0,normal
2455,42131,Hissar,2025-04-19 12:00:00,40.0,0,normal
2537,42131,Hissar,2025-04-25 07:00:00,40.1,0,normal
2538,42131,Hissar,2025-04-25 08:00:00,40.7,0,normal
2539,42131,Hissar,2025-04-25 09:00:00,40.8,0,normal
2540,42131,Hissar,2025-04-25 10:00:00,40.7,0,normal
2541,42131,Hissar,2025-04-25 11:00:00,40.9,0,normal
2561,42131,Hissar,2025-04-26 07:00:00,40.0,0,normal
2562,42131,Hissar,2025-04-26 08:00:00,40.3,0,normal
2585,42131,Hissar,2025-04-27 07:00:00,40.0,0,normal

In [126]:
high_temp_consensus = (
    df[df["temperature"] >= 40]
    .groupby("timestamp")
    .agg(
        station_count=("station_id", "nunique"),
        average_temperature=("temperature", "mean"),
        max_temperature=("temperature", "max"),
        min_temperature=("temperature", "min")
    )
    .sort_values(
        ["station_count", "average_temperature"],
        ascending=False
    )
)

print("Timestamps with multiple stations >= 40°C:")

display(
    high_temp_consensus[
        high_temp_consensus["station_count"] >= 2
    ].head(20)
)

Timestamps with multiple stations >= 40°C:

,station_count,average_temperature,max_temperature,min_temperature
timestamp,,,,
2025-06-09 10:00:00,4,42.775,44.0,42.1
2025-06-10 10:00:00,4,42.525,44.0,41.6
2025-06-09 09:00:00,4,42.500,43.0,42.2
2025-06-10 09:00:00,4,42.425,44.0,41.3
2025-06-11 10:00:00,4,42.425,44.0,41.5
2025-06-11 09:00:00,4,42.325,43.0,41.9
2025-06-10 11:00:00,4,42.300,44.0,41.2
2025-06-09 11:00:00,4,42.225,43.0,41.6
2025-06-12 09:00:00,4,42.100,42.6,41.7
2025-06-09 08:00:00,4,42.075,43.0,41.7
2025-06-12 10:00:00,4,42.075,42.4,41.7
2025-06-11 08:00:00,4,42.050,43.0,41.5
2025-06-11 11:00:00,4,41.900,43.0,41.1
2025-05-16 10:00:00,4,41.875,42.4,41.4
2025-05-18 10:00:00,4,41.875,42.7,40.8
2025-06-12 11:00:00,4,41.875,42.1,41.3
2025-05-16 09:00:00,4,41.850,42.8,40.5
2025-06-08 09:00:00,4,41.850,43.0,41.1
2025-06-08 10:00:00,4,41.850,43.0,41.1
2025-06-10 08:00:00,4,41.700,43.0,40.6

In [131]:
from src.spatial_analysis import (
    create_distance_matrix,
    get_neighbors,
    get_neighbor_average,
    calculate_spatial_deviation,
    get_neighbor_consensus
)

from src.diagnosis import (
    classify_weather_vs_sensor,
    correct_value
)

from src import sensor_health

print("All  modules imported successfully.")

All  modules imported successfully.

In [155]:
%%writefile src/person3_pipeline.py

import pandas as pd

from src.spatial_analysis import get_neighbor_consensus
from src.diagnosis import classify_weather_vs_sensor, correct_value
from src import sensor_health


def diagnose_sensor_observation(
    df,
    station_id,
    timestamp,
    parameter,
    distance_matrix,
    ml_anomaly=False,
    temporal_anomaly=False,
    current_health=100,
    last_valid_value=None,
    max_distance_km=100,
    spatial_threshold=5.0
):
    """
    Complete Person-3 pipeline for one observation.

    Spatial analysis
        ↓
    Diagnosis
        ↓
    Correction
        ↓
    Sensor health
    """

    # --------------------------------------------------
    # 1. Get target observation
    # --------------------------------------------------

    target = df[
        (df["station_id"] == station_id) &
        (df["timestamp"] == timestamp)
    ]

    if target.empty:
        raise ValueError(
            "No observation found for the given station and timestamp."
        )

    station_value = target.iloc[0][parameter]

    # --------------------------------------------------
    # 2. Spatial analysis
    # --------------------------------------------------

    consensus = get_neighbor_consensus(
        df=df,
        station_id=station_id,
        timestamp=timestamp,
        parameter=parameter,
        distance_matrix=distance_matrix,
        max_distance_km=max_distance_km
    )

    neighbor_average = consensus["neighbor_average"]

    neighbor_count = consensus["neighbor_count"]

    normal_neighbors = consensus["normal_neighbors"]

    anomalous_neighbors = consensus["anomalous_neighbors"]

    # --------------------------------------------------
    # 3. Diagnosis
    # --------------------------------------------------

    classification, evidence_score, reasons = (
        classify_weather_vs_sensor(
            ml_anomaly=ml_anomaly,
            temporal_anomaly=temporal_anomaly,
            station_value=station_value,
            neighbor_average=neighbor_average,
            spatial_threshold=spatial_threshold
        )
    )

    # --------------------------------------------------
    # 4. Correction
    # --------------------------------------------------

    if classification == "Sensor Fault":

        corrected_value = correct_value(
            original_value=station_value,
            neighbor_average=neighbor_average,
            last_valid_value=last_valid_value
        )

    else:

        corrected_value = station_value

    # --------------------------------------------------
    # 5. Determine fault type
    # --------------------------------------------------

    fault_type = None

    if classification == "Sensor Fault":

        if parameter == "temperature":

            if station_value > 40:
                fault_type = "temperature_spike"

            elif station_value < -20:
                fault_type = "temperature_drop"

            else:
                fault_type = "temperature_spike"

        elif parameter == "humidity":

            fault_type = "humidity_spike"

        elif parameter == "pressure":

            fault_type = "pressure_spike"

    # --------------------------------------------------
    # 6. Update sensor health
    # --------------------------------------------------

    new_health = current_health

    if fault_type is not None:

        new_health = sensor_health.update_health_score(
            current_score=current_health,
            fault_type=fault_type
        )

    health_status = sensor_health.get_health_status(
        new_health
    )

    # --------------------------------------------------
    # 7. Spatial difference
    # --------------------------------------------------

    if pd.isna(neighbor_average):

        spatial_difference = None

    else:

        spatial_difference = abs(
            station_value - neighbor_average
        )

    # --------------------------------------------------
    # 8. Final result
    # --------------------------------------------------

    result = {
        "station_id": station_id,
        "timestamp": timestamp,
        "parameter": parameter,

        "original_value": station_value,

        "neighbor_count": neighbor_count,
        "normal_neighbors": normal_neighbors,
        "anomalous_neighbors": anomalous_neighbors,

        "neighbor_average": neighbor_average,
        "spatial_difference": spatial_difference,

        "ml_anomaly": ml_anomaly,
        "temporal_anomaly": temporal_anomaly,

        "classification": classification,
        "evidence_score": evidence_score,
        "reasons": reasons,

        "fault_type": fault_type,

        "corrected_value": corrected_value,

        "health_score": new_health,
        "health_status": health_status
    }

    return result


def process_observations(
    df,
    observations,
    distance_matrix,
    ml_anomaly_col="ml_anomaly",
    temporal_anomaly_col="temporal_anomaly",
    parameter="temperature",
    current_health=100,
    max_distance_km=100,
    spatial_threshold=5.0
):
    """
    Process multiple observations through the Person-3 pipeline.

    Returns a DataFrame containing:
    spatial analysis,
    diagnosis,
    correction,
    and sensor health.
    """

    results = []

    health_scores = {}

    for _, row in observations.iterrows():

        station_id = row["station_id"]
        timestamp = row["timestamp"]

        station_health = health_scores.get(
            station_id,
            current_health
        )

        ml_anomaly = bool(
            row.get(ml_anomaly_col, False)
        )

        temporal_anomaly = bool(
            row.get(temporal_anomaly_col, False)
        )

        result = diagnose_sensor_observation(
            df=df,
            station_id=station_id,
            timestamp=timestamp,
            parameter=parameter,
            distance_matrix=distance_matrix,
            ml_anomaly=ml_anomaly,
            temporal_anomaly=temporal_anomaly,
            current_health=station_health,
            max_distance_km=max_distance_km,
            spatial_threshold=spatial_threshold
        )

        health_scores[station_id] = result["health_score"]

        results.append(result)

    return pd.DataFrame(results)

Overwriting src/person3_pipeline.py

In [151]:
from src.person3_pipeline import diagnose_sensor_observation

print(" integration pipeline loaded successfully.")

 integration pipeline loaded successfully.

In [152]:
stations = (
    df[
        [
            "station_id",
            "station_name",
            "latitude",
            "longitude"
        ]
    ]
    .drop_duplicates("station_id")
    .reset_index(drop=True)
)

distance_matrix = create_distance_matrix(stations)

print("Distance matrix ready.")

Distance matrix ready.

In [153]:
result = diagnose_sensor_observation(
    df=df,
    station_id=42131,
    timestamp=pd.Timestamp("2025-01-01 00:00:00"),
    parameter="temperature",
    distance_matrix=distance_matrix,

    ml_anomaly=False,
    temporal_anomaly=False,

    current_health=100
)

print(result)

{'station_id': 42131, 'timestamp': Timestamp('2025-01-01 00:00:00'), 'parameter': 'temperature', 'original_value': np.float64(5.4), 'neighbor_count': 1, 'normal_neighbors': 1, 'anomalous_neighbors': 0, 'neighbor_average': np.float64(7.7), 'spatial_difference': np.float64(2.3), 'ml_anomaly': False, 'temporal_anomaly': False, 'classification': 'Likely Weather Event', 'evidence_score': 0, 'reasons': [], 'fault_type': None, 'corrected_value': np.float64(5.4), 'health_score': 100, 'health_status': 'GREEN'}

In [140]:
for key, value in result.items():
    print(f"{key}: {value}")

station_id: 42131
timestamp: 2025-01-01 00:00:00
parameter: temperature
original_value: 5.4
neighbor_count: 1
normal_neighbors: 1
anomalous_neighbors: 0
neighbor_average: 7.7
spatial_difference: 2.3
ml_anomaly: False
temporal_anomaly: False
classification: Likely Weather Event
evidence_score: 0
reasons: []
fault_type: None
corrected_value: 5.4
health_score: 100
health_status: GREEN

In [141]:
demo_df = df.copy()

In [142]:
candidate_times = (
    df.groupby("timestamp")
    .agg(
        station_count=("station_id", "nunique"),
        avg_temperature=("temperature", "mean"),
        min_temperature=("temperature", "min"),
        max_temperature=("temperature", "max")
    )
)

candidates = candidate_times[
    (candidate_times["station_count"] >= 2) &
    (candidate_times["avg_temperature"].between(20, 35))
]

display(candidates.head(20))

,station_count,avg_temperature,min_temperature,max_temperature
timestamp,,,,
2025-01-04 10:00:00,5,20.28,18.6,22.4
2025-01-19 08:00:00,5,21.08,20.0,24.0
2025-01-19 09:00:00,5,22.96,21.0,25.4
2025-01-19 10:00:00,5,22.54,21.1,24.2
2025-01-19 11:00:00,5,21.86,20.2,24.0
2025-01-19 12:00:00,5,21.28,20.2,22.6
2025-01-20 07:00:00,5,21.16,20.2,22.2
2025-01-20 08:00:00,5,22.06,21.3,22.9
2025-01-20 09:00:00,5,22.92,21.4,24.2
2025-01-20 10:00:00,5,22.38,21.3,23.0
2025-01-20 11:00:00,5,21.54,20.6,22.1
2025-01-20 12:00:00,5,20.80,19.8,22.4
2025-01-21 07:00:00,5,20.78,19.7,21.7
2025-01-21 08:00:00,5,21.74,20.7,22.6
2025-01-21 09:00:00,5,22.34,21.2,23.4
2025-01-21 10:00:00,5,21.84,20.8,22.6
2025-01-21 11:00:00,5,21.06,19.9,22.0
2025-01-21 12:00:00,5,20.76,20.0,21.4
2025-01-22 07:00:00,5,20.90,19.5,21.7
2025-01-22 08:00:00,5,21.86,20.5,22.8

In [143]:
demo_time = candidates.index[0]

# See stations at this timestamp
demo_rows = df[df["timestamp"] == demo_time].copy()

# Choose the first station
demo_station = demo_rows.iloc[0]["station_id"]

# Create demo copy
demo_df = df.copy()

# Inject 55°C fault
mask = (
    (demo_df["station_id"] == demo_station) &
    (demo_df["timestamp"] == demo_time)
)

original_value = demo_df.loc[mask, "temperature"].iloc[0]

demo_df.loc[mask, "temperature"] = 55.0

print("Demo timestamp:", demo_time)
print("Demo station:", demo_station)
print("Original value:", original_value)
print("Injected value:", demo_df.loc[mask, "temperature"].iloc[0])

Demo timestamp: 2025-01-04 10:00:00
Demo station: 42131
Original value: 21.8
Injected value: 55.0

In [144]:
result = diagnose_sensor_observation(
    df=demo_df,
    station_id=demo_station,
    timestamp=demo_time,
    parameter="temperature",
    distance_matrix=distance_matrix,

    # These represent the outputs that Person 2
    # will eventually provide.
    ml_anomaly=True,
    temporal_anomaly=True,

    current_health=100
)

for key, value in result.items():
    print(f"{key}: {value}")

station_id: 42131
timestamp: 2025-01-04 10:00:00
parameter: temperature
original_value: 55.0
neighbor_count: 1
normal_neighbors: 1
anomalous_neighbors: 0
neighbor_average: 22.4
spatial_difference: 32.6
ml_anomaly: True
temporal_anomaly: True
classification: Sensor Fault
evidence_score: 3
reasons: ['ML anomaly detected', 'Temporal deviation detected', 'Value differs significantly from nearby stations']
fault_type: temperature_spike
corrected_value: 22.4
health_score: 85
health_status: GREEN

In [145]:
weather_time = pd.Timestamp("2025-06-09 10:00:00")

display(
    df[
        df["timestamp"] == weather_time
    ][
        [
            "station_id",
            "station_name",
            "temperature",
            "is_anomaly",
            "fault_type"
        ]
    ].sort_values("temperature")
)

       station_id station_name  temperature  is_anomaly fault_type
12144       42139       Meerut         37.0           0     normal
38165       42182   Safdarjung         42.1           0     normal
20661       42176       Rohtak         42.3           0     normal
3620        42131       Hissar         42.7           0     normal
29404       42181        Palam         44.0           0     normal

In [156]:
import importlib
import src.person3_pipeline as person3_pipeline

importlib.reload(person3_pipeline)

from src.person3_pipeline import (
    diagnose_sensor_observation,
    process_observations
)

print("Person-3 pipeline ready.")

Person-3 pipeline ready.

In [157]:
test_observations = pd.DataFrame([
    {
        "station_id": demo_station,
        "timestamp": demo_time,
        "ml_anomaly": True,
        "temporal_anomaly": True
    }
])

display(test_observations)

   station_id           timestamp  ml_anomaly  temporal_anomaly
0       42131 2025-01-04 10:00:00        True              True

In [158]:
person3_results = process_observations(
    df=demo_df,
    observations=test_observations,
    distance_matrix=distance_matrix,
    parameter="temperature"
)

display(person3_results)

,station_id,timestamp,parameter,original_value,neighbor_count,normal_neighbors,anomalous_neighbors,neighbor_average,spatial_difference,ml_anomaly,temporal_anomaly,classification,evidence_score,reasons,fault_type,corrected_value,health_score,health_status
0,42131,2025-01-04 10:00:00,temperature,55.0,1,1,0,22.4,32.6,True,True,Sensor Fault,3,"[ML anomaly detected, Temporal deviation detec...",temperature_spike,22.4,85,GREEN

In [159]:
!pwd
!git status

/content/SATARK_AI
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/diagnosis.py
	modified:   src/sensor_health.py
	modified:   src/spatial_analysis.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	src/person3_pipeline.py

no changes added to commit (use "git add" and/or "git commit -a")

In [160]:
!git status --short

 M src/diagnosis.py
 M src/sensor_health.py
 M src/spatial_analysis.py
?? src/person3_pipeline.py

In [161]:
!git fetch origin
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/diagnosis.py
	modified:   src/sensor_health.py
	modified:   src/spatial_analysis.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	src/person3_pipeline.py

no changes added to commit (use "git add" and/or "git commit -a")

In [162]:
!git add src/diagnosis.py src/sensor_health.py src/spatial_analysis.py src/person3_pipeline.py

In [163]:
!git diff --cached --stat

 src/diagnosis.py        |  82 ++++++++++++++++
 src/person3_pipeline.py | 255 ++++++++++++++++++++++++++++++++++++++++++++++++
 src/sensor_health.py    |  65 ++++++++++++
 src/spatial_analysis.py | 222 +++++++++++++++++++++++++++++++++++++++++
 4 files changed, 624 insertions(+)

In [166]:
!git log -1 --oneline
!git remote -v

f96cd10 (HEAD -> main, origin/main, origin/HEAD) Add P4 dashboard integration notebook
origin	https://github.com/anushah-200/SATARK_AI (fetch)
origin	https://github.com/anushah-200/SATARK_AI (push)